### ISSUE TITLE
division by zero error when autograded questions are worth zero points

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#154]
**Describe the bug**
An assignment all of whose autograded questions are worth zero points will cause the autograder to fail due to division by zero.

**To Reproduce**
1. Create an assignment with an autograded question worth zero points and no other questions.
2. Compile it using otter assign.
3. Upload the autograder to gradescope.
4. Submit an assignment to gradescope.

**Expected behavior**
The autograder should correctly assign zero points

**Versions**
Python 3.8.5, otter 1.1.3

**Additional context**
A workaround is to assign one point to a dummy question that comes with a hidden test that is always true/correct.
Having a zero-point assignment is useful when all the questions in the assignment that have nonzero points are manually graded, and the questions that have zero points ask for the student's name etc.

**Comment by chrispyles** [comment]
@champoll can you provide a stack trace for this error so that I can pinpoint the code that needs to be changed?

**Comment by champoll** [comment]
```
Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 30, in <module>
    run_autograder(config)
  File "/root/miniconda3/envs/otter-gradescope-env/lib/python3.7/site-packages/otter/generate/run_autograder/__init__.py", line 28, in main
    output = run_autograder(config)
  File "/root/miniconda3/envs/otter-gradescope-env/lib/python3.7/site-packages/otter/generate/run_autograder/run_autograder.py", line 133, in run_autograder
    output = scores.to_gradescope_dict(config)
  File "/root/miniconda3/envs/otter-gradescope-env/lib/python3.7/site-packages/otter/execute/results.py", line 244, in to_gradescope_dict
    output["score"] = self.total / self.possible * options["points_possible"]
ZeroDivisionError: division by zero
```

**Comment by chrispyles** [comment]
Version 1.1.6 (just released) should fix this issue.
