### ISSUE TITLE
Failed to run "xelatex .\notebook.tex -quiet" command on Windows 10

### ISSUE THREAD

**Issue by richardcherron** [ucbds-infra/otter-grader#164]
The [otter-grader documentation](https://otter-grader.readthedocs.io/en/latest/index.html) says that Windows 10 users should run `otter` as a module (`python3 -m otter`). However, I followed the tutorial on Windows 10 with Python 3.8.3, and `otter assign` failed with the errors below. My Anaconda installation only has Python 3, so I ran `python -m otter`.

```
(base) C:\Users\richa\Documents\tutorial-1\assign>python -m otter assign assign-demo.ipynb dist
Generating views...
Generating solutions PDF...
There was an error generating your LaTeX
Showing concise error message
============================================================
Failed to run "xelatex .\notebook.tex -quiet" command:
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
?
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?.

============================================================
Generating autograder zipfile...
Running tests...
Traceback (most recent call last):
  File "C:\Users\richa\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\richa\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\__main__.py", line 8, in <module>
    run_otter()
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\run.py", line 43, in run_otter
    args.func(args)
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\assign\__init__.py", line 123, in main
    run_tests(result / 'autograder' / master.name, debug=args.debug, seed=seed)
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\assign\utils.py", line 161, in run_tests
    assert results.total == results.possible, "Some autograder tests failed:\n\n" + pprint.pformat(results, indent=2)
AssertionError: Some autograder tests failed:

{ 'q1': { 'hidden': False,
          'incorrect': False,
          'name': 'q1',
          'possible': 1,
          'score': 1.0,
          'test': tests/q1.py passed!},
  'q2': { 'hidden': False,
          'incorrect': False,
          'name': 'q2',
          'possible': 1,
          'score': 1.0,
          'test': tests/q2.py passed!},
  'q3': { 'hidden': False,
          'incorrect': True,
          'name': 'q3',
          'possible': 1,
          'score': 0.0,
          'test':    tests/q3.py

Test result:
Trying:
    len(data["flavor"].unique()) == 4
Expecting:
    True
**********************************************************************
Line 1, in tests/q3.py 0
Failed example:
    len(data["flavor"].unique()) == 4
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\richa\anaconda3\lib\doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest tests/q3.py 0[0]>", line 1, in <module>
        len(data["flavor"].unique()) == 4
    NameError: name 'data' is not defined
}}
```

If I export assign-demo.ipynb to a .tex file, I can compile it with either pdflatex or xelatex.

For what it is worth, I hope to use otter-grader with Gradescope and Canvas. My home and work machines are Windows 10. Is there a *nix environment that works better with otter-grader? Cygwin? Windows Subsystem for Linux?

```
(base) C:\Users\richa\Documents\tutorial-1\assign>python --version
Python 3.8.3
```

**Comment by chrispyles** [comment]
For the LaTeX issue, what version of nbconvert do you have installed? Otter uses nbconvert to run LaTeX under the hood and the error you're getting looks like a problem that's taking place in how nbconvert is calling LaTeX, not something in Otter.

Regarding the tests failing issue, can you run otter assign again with the `--debug` flag and send the output? (This option prevents Otter from ignoring errors during execution and instead raises them to allow you to see what's going on.)

**Comment by richardcherron** [comment]
My `nbconvert` version is 5.6.1. FWIW, this version came with a recent install of Anaconda, and I could upgrade `nbconvert` to 6.0.3 through 6.0.7.

Here is the `otter assign` output with `--debug`:

```
(base) C:\Users\richa\Documents\tutorial-1\assign>python -m otter assign assign-demo.ipynb dist --debug
Generating views...
Generating solutions PDF...
There was an error generating your LaTeX
Showing concise error message
============================================================
Failed to run "xelatex .\notebook.tex -quiet" command:
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
?
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?.

============================================================
Generating autograder zipfile...
Running tests...
Traceback (most recent call last):
  File "C:\Users\richa\anaconda3\lib\sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\richa\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\__main__.py", line 8, in <module>
    run_otter()
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\run.py", line 43, in run_otter
    args.func(args)
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\assign\__init__.py", line 123, in main
    run_tests(result / 'autograder' / master.name, debug=args.debug, seed=seed)
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\assign\utils.py", line 157, in run_tests
    results = grade_notebook(
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\execute\__init__.py", line 105, in grade_notebook
    global_env = execute_notebook(nb, secret, initial_env, ignore_errors=ignore_errors, cwd=cwd, test_dir=test_dir, seed=seed)
  File "C:\Users\richa\anaconda3\lib\site-packages\otter\execute\execute_notebook.py", line 127, in execute_notebook
    line = re.sub(r"otter\.Notebook\(.*?\)", f"otter.Notebook(\"{test_dir}\")", line)
  File "C:\Users\richa\anaconda3\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\richa\anaconda3\lib\re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\richa\anaconda3\lib\re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\richa\anaconda3\lib\sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \U at position 18

(base) C:\Users\richa\Documents\tutorial-1\assign>
```

**Comment by chrispyles** [comment]
re: nbconvert, what version of otter are you running? you can get this with `python -m otter --version`. I ask because otter<2.0.0 doesn't support nbconvert>=6.0.0 (but we are in pre-release w/ otter v2 and this has been patched)

If you want to try upgrading to the next pre-release version of otter when it comes out, you can try upgrading nbconvert also and see if that resolves the latex error.

re: tests failing, it looks like some of the regex substitutions otter uses when executing the notebook code ran into an escape `\U` that Python's `re` module can't parse. Any idea if this occurs in your code/why this might be the case?

**Comment by richardcherron** [comment]
I am using Otter Grader version 1.1.6:
```
(base) C:\Users\richa\Documents\tutorial-1>python -m otter --version

  _________        __          __
 /  _____  \    __|  |__    __|  |__
|  /     \  |  |__    __|  |__    __|   _______    _  _____
| |       | |     |  |        |  |     |  ___  |  | |/ ____|
| |       | |     |  |        |  |     | |___| |  |   /
| |       | |     |  |        |  |     | ______|  |  |
|  \_____/  |     |  |_       |  |_    | |_____   |  |
 \_________/       \ __|       \ __|    \______|  |__|
                                                v1.1.6


Python version: 3.8.3
Otter-Grader version: 1.1.6
```
I am using `assignment-demo.ipynb` from the Otter Grader tutorial.

I made a very simple demo notebook ([my-demo.zip](https://github.com/ucbds-infra/otter-grader/files/5766276/my-demo.zip)
), and it passes all tests, locally and on Gradescope. However, locally and on Gradescope, `xelatex .\notebook.tex -quiet` fails with the same error above. If I receive this error on Gradescope, too, does that suggest the error is not due to path differences between Windows and *nix?

Either way, this is not an urgent fix (at least on my end) since I can create Otter Grade-able notebooks and students can manually generate pdfs when I want to manually grade questions.

Thanks for your help!

**Comment by chrispyles** [comment]
Yeah, it might be worth considering upgrading to `otter-grader==2.0.0.b6` (support for nbconvert v6) and `nbconvert>=6.0.0` and see if that resolves the xelatex error, but regardless I think it's a fix that needs to be made on nbconvert's end. 

Going to close this thread but please reopen if I've missed something!
