### ISSUE TITLE
otter run creates zipfile error

### ISSUE THREAD

**Issue by connermanuel** [ucbds-infra/otter-grader#219]
**Describe the bug**
otter run errors out while trying to open the autograder zipfile. The error does not persist in otter grade.

**To Reproduce**

```
>  otter run -a ./autograder.zip student-demo-passesAll.ipynb --debug // I ran this both with and without the -a flag
...
Traceback (most recent call last):
  File "c:\users\itsco\envs\esk\lib\site-packages\otter\run\__init__.py", line 52, in main
    run_autograder(ag_dir, logo=logo, debug=debug)
  File "c:\users\itsco\envs\esk\lib\site-packages\otter\run\run_autograder\__init__.py", line 48, in main
    output = run_autograder(options)
  File "c:\users\itsco\envs\esk\lib\site-packages\otter\run\run_autograder\run_autograder.py", line 118, in run_autograder
    with zipfile.ZipFile(zips[0])  as zf:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\itsco\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\itsco\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\itsco\Envs\esk\Scripts\otter.exe\__main__.py", line 7, in <module>
  File "c:\users\itsco\envs\esk\lib\site-packages\otter\runner.py", line 56, in run_otter
    args.func(**kwargs)
  File "c:\users\itsco\envs\esk\lib\site-packages\otter\run\__init__.py", line 62, in main
    shutil.rmtree(dp)
  File "c:\users\itsco\appdata\local\programs\python\python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\itsco\appdata\local\programs\python\python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\itsco\appdata\local\programs\python\python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\itsco\appdata\local\programs\python\python39\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\itsco\appdata\local\programs\python\python39\lib\shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\itsco\\AppData\\Local\\Temp\\tmpizjdftoz\\autograder\\submission'
```

**Versions**
Windows 10
python 3.9.1
otter 2.1.3

WSL - Ubuntu 20.04 (note that ubuntu only produces the first error)
python 3.8.5
otter 2.1.3

**Comment by connermanuel** [comment]
While on the subject, what would you suggest to be the best way to grade notebooks in a dockerized environment (as in calling the program itself in a docker container)? Seeing as otter grade would create a docker in docker environment, this is the reason why I'm trying to run otter run.

**Comment by chrispyles** [comment]
Can you share the autograder.zip? It looks like otter is executing a line that happens when it's trying to grade zip files not .ipynb files. Is this from the tutorial?

**Comment by connermanuel** [comment]
[autograder.zip](https://github.com/ucbds-infra/otter-grader/files/5969820/autograder.zip)
Here is the autograder.zip. Both the AG zip file and the student notebook are from the tutorial.

I should mention that running the `otter.api.grade_submission` endpoint results in the same error.

**Comment by chrispyles** [comment]
OK I think this is an issue with the instructions for the tutorial. I've updated them- can you try again?

**Comment by connermanuel** [comment]
Great, works perfectly. Not even sure what I changed to be entirely honest but we're all good now. Thanks!

**Comment by connermanuel** [comment]
Ah I see, the old `tutorial.zip` file game with `zips: True` by default. Thanks for the clarification!
