### ISSUE TITLE
Cannot open via jupyter notebook on windows 10

### ISSUE THREAD

**Issue by alexy1234** [ucbds-infra/otter-grader#25]
Steps to replicate on windows 10 after pip installation and docker pull for image:

1) run jupyter notebook in cmd
2) open demo notebook

stack trace:
[I 00:19:26.496 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=53992a9a47de2e7a1d1ee95fb62c2c82c8a43e8bc4710ed6
[I 00:19:26.498 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:19:26.501 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=53992a9a47de2e7a1d1ee95fb62c2c82c8a43e8bc4710ed6
[I 00:19:26.951 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 00:19:32.496 NotebookApp] Notebook demo.ipynb is not trusted
[E 00:19:34.709 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 526, in get
        value = obj._trait_values[self.name]
    KeyError: 'loop'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
        type=mtype))
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 326, in wrapper
        yielded = next(result)
      File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
        self.start_restarter()
      File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\ioloop\manager.py", line 49, in start_restarter
        kernel_manager=self, loop=self.loop,
      File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 554, in __get__
        return self.get(obj, cls)
      File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 533, in get
        value = self._validate(obj, dynamic_default())
      File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 589, in _validate
        value = self.validate(obj, value)
      File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 1675, in validate
        self.error(obj, value)
      File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 1522, in error
        raise TraitError(e)
    traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x000001B7AD3CFA20>) was specified.
[E 00:19:34.750 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "87",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Sec-Fetch-Dest": "empty",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|0523390e|95df01d3ff9669c08e63fc9e8fa03f74|1581665725",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8888/notebooks/demo.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
      "Cookie": "_xsrf=2|0523390e|95df01d3ff9669c08e63fc9e8fa03f74|1581665725; username-localhost-8888=\"2|1:0|10:1581754766|23:username-localhost-8888|44:MjM5YTk3ODRmMDdhNGNhNzljNTc2Y2FkNTNhMDNjYTE=|39ea2353eb332be352794c09b805cb370361575c3b7f2d3c3f7f6e02877da4e9\""
    }
[E 00:19:34.763 NotebookApp] 500 POST /api/sessions (::1) 176.94ms referer=http://localhost:8888/notebooks/demo.ipynb
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Program Files\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\Anaconda3\lib\asyncio\base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

**Comment by chrispyles** [comment]
not an otter issue
