### ISSUE TITLE
Otter-grader failing on R code that uses the new pipe operator: |>

### ISSUE THREAD

**Issue by ttimbers** [ucbds-infra/otter-grader#379]
There is a new native pipe operator, `|>`, in base R and when I use it on an Otter-grader assignment graded in Gradescope the autograder fails. 

```
The results uploaded to Gradescope were not formatted correctly. Please see
http://gradescope-autograders.readthedocs.io/en/latest/specs/#output-format
for more details.

Use the "Debug via SSH" button below to debug this issue.


We did not receive any results for this submission.

The autograder produced the following output:

R[write to console]: 

processing file: /autograder/submission/worksheet1.Rmd

‏
  _________        __          __               
 /  _____  \    __|  |__    __|  |__               
|  /     \  |  |__    __|  |__    __|   _______    _  _____
| |       | |     |  |        |  |     |  ___  |  | |/ ____|
| |       | |     |  |        |  |     | |___| |  |   /    
| |       | |     |  |        |  |     | ______|  |  |
|  \_____/  |     |  |_       |  |_    | |_____   |  |
 \_________/       \ __|       \ __|    \______|  |__|
                                                v3.0.2


  |......................................................................| 100%
R[write to console]: output file: /autograder/submission/worksheet1.r


R[write to console]: Error in parse(text = script) : <text>:61:34: unexpected '>'
60: ## ----tags=c()-----------------------------------------------------------------
61: female_penguins <- penguins_csv |>
                                     ^

Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 11, in <module>
    run_autograder('/autograder')
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/__init__.py", line 51, in main
    output = run_autograder(options)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/r_adapter/run_autograder.py", line 92, in run_autograder
    output = r(f"""ottr::run_autograder("{fp}")""")[0]
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 438, in __call__
    res = self.eval(p)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/rinterface.py", line 680, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in parse(text = script) : <text>:61:34: unexpected '>'
60: ## ----tags=c()-----------------------------------------------------------------
61: female_penguins <- penguins_csv |>
```

From the error message - perhaps it's an issue with parsing R via `rpy2`?

**Comment by ttimbers** [comment]
Actually - I think it is the version of R - for example, if on R < 4.1.0 (where the operator does not yet exist) I get a similar error:

```
R version 4.0.5 (2021-03-31)

5 |> print()

Error in parse(text = x, srcfile = src): <text>:1:4: unexpected '>'
1: 5 |>
       ^
Traceback:
```

So, we need to be able to update the version of R installed by the autograder. Where would I specify that for R? In `environment.yml`? Or in the `setup.sh` file?

**Comment by chrispyles** [comment]
I think the version of R provided by the default conda channel is older, but it looks like conda-forge has [R 4.1.1](https://anaconda.org/conda-forge/r-base/labels) (?)

I think replacing `r-base` with `conda-forge::r-base` in the environment.yml should do the trick.

**Comment by ttimbers** [comment]
OK, so both @ShanEllis and I independently ran into this, and it is indeed `environment.yml` where we need to set something like `r-base=4.1.1` and that works in my hands. It is also important to set `environment: environment.yml` in `# ASSIGNMENT CONFIG` at the top of the notebook so that the `environment.yml` where that is specified will get sourced when the `autograding.zip` is generated. This was not super clear to me in the docs. Happy to send a PR to make this clearer if it would be welcomed?

**Comment by chrispyles** [comment]
Yes, please feel free to submit a PR!

**Comment by chrispyles** [comment]
Closing this issue as it seems like this issue was resolved but please feel free to reopen if I've missed anything.
