### ISSUE TITLE
Issues running tests with Rmd notebooks

### ISSUE THREAD

**Issue by hgibling** [ucbds-infra/otter-grader#386]
Hello,

I've gotten through the full workflow with the ipynb demo files in the tutorial documation, but I want to use otter to grade Rmd notebooks.

I have the following setup so far (all files can be found on my [github](https://github.com/hgibling/otter-test)):
```
cd ~/Documents/otter-test

.
├── TestAssignment.Rmd
├── dist
│   ├── autograder
│   │   ├── TestAssignment.Rmd
│   │   └── tests
│   │       ├── Question1.R
│   │       └── Question2.R
│   └── student
│       ├── TestAssignment.Rmd
│       └── tests
│           ├── Question1.R
│           └── Question2.R
└── submissions
    ├── Student1-Correct-TestAssignment.Rmd
    └── Student2-Wrong-TestAssignment.Rmd

```

Question1 has one open and one hidden test, and Question2 has 2 hidden tests. The student distribution notebook looks fine to me, and I copied them and put in answers to make the two submission files. I've run into three issues:

1. In R, the relative path to `tests` does not work in the student notebook, I need the full path (not the end of the world; the `dist/autograder` notebook can use relative paths fine):
```
> setwd("~/Documents/otter-test/dist/student/")
> 
> library(testthat)
> library(ottr)
>
> ice_cream <- "vanilla" # YOUR CODE HERE
> . = ottr::check("tests/Question1.R")
cannot open file 'tests/Question1.R': No such file or directoryError in file(filename, "r") : cannot open the connection
> getwd()
[1] "/Users/hgibling/Documents/otter-test/dist/student"
> . = ottr::check("~/Documents/otter-test/dist/student/tests/Question1.R")
All tests passed!
```

2. While the tests work appropriately in the original raw notebook, in the student notebooks (and in the `dist/autograder` notebook) the tests pass when the answer is blatantly wrong:
```
> getwd()
[1] "/Users/hgibling/Documents/otter-test/dist/student"
> ice_cream <- 13 # YOUR CODE HERE
> . = ottr::check("~/Documents/otter-test/dist/student/tests/Question1.R")
All tests passed!

###

> setwd("~/Documents/otter-test/dist/autograder/")
> ice_cream <- "chocolate" #SOLUTION
> . = ottr::check("tests/Question1.R")
All tests passed!
> ice_cream <- 13 #SOLUTION
> . = ottr::check("tests/Question1.R")
All tests passed!
```

3. I imagine the previous issue might have something to do with not being able to run `otter check` in terminal. Since I'm pretending to be a student, I am supplying the path to the student tests created after `otter assign` in `dist`:
```
cd ~/Documents/otter-test/submissions
otter check Student1-Correct-TestAssignment.Rmd -t ~/Documents/otter-test/dist/student/tests -q Question1 

Traceback (most recent call last):
  File "/Users/hgibling/miniconda3/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/cli.py", line 55, in check_cli
    return check(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/check/__init__.py", line 77, in main
    raise e
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/check/__init__.py", line 50, in main
    assert os.path.isfile(test_path), "Test {} does not exist".format(question)
AssertionError: Test Question1.R does not exist
```

I'm not sure what's happening. Any ideas?

**Comment by hgibling** [comment]
```
otter --version

Python version: 3.7.9
Otter-Grader version: 3.0.6
```

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16

other attached packages:
[1] stringr_1.4.0  ottr_1.0.0     testthat_3.0.4
```

**Comment by chrispyles** [comment]
Hi @hgibling.

Regarding the example you posted, there are a few issues with the syntax in the provided example.

1. The `BEGIN ASSIGNMENT` block should not be in an executable R block, just a plain markdown code block (like the `BEGIN QUESTION` blocks):

````
```
# BEGIN ASSIGNMENT
generate: true
```
````

2. With Ottr v1, the tests no longer use calls to `testthat::test_that` as a requirement; instead, a test's passing or failing is determined by whether it raises an error. Since `testthat::test_that` actually _swallows_ errors raised by expectations run inside it, the tests will always pass because there's never an exception raised, even if the test fails. Instead, just use the `expect_*` functions directly:

````
```{r}
## Test ##
testthat::expect_that(ice_cream, testthat::is_a("character"))
```
````

3. Otter Check does not work with R assignments, only Python assignments.

Keeping the above in mind, and fixing the syntax in the Rmd file in your repo, everything worked as expected for me with ottr v1.1.1 and RStudio.

**Comment by chrispyles** [comment]
Here's the Rmd file from your repo with the syntax issues corrected.

[TestAssignment.Rmd.txt](https://github.com/ucbds-infra/otter-grader/files/7141200/TestAssignment.Rmd.txt)

**Comment by johnchaston** [comment]
Thanks, I had same issues, appreciate the updated documentation which I had missed before.

**Comment by hgibling** [comment]
Thanks for the clarifications!

I am now stuck trying to grade the assignments. Using the updated assignment, I reran `git assign TestAssignment.Rmd dist --v1`, and manually made the student 'submissions': 
```
.
├── TestAssignment.Rmd
├── dist
│   ├── autograder
│   │   ├── TestAssignment.Rmd
│   │   ├── autograder.zip
│   │   ├── otter_config.json
│   │   └── tests
│   │       ├── Question1.R
│   │       └── Question2.R
│   └── student
│       ├── TestAssignment.Rmd
│       └── tests
│           ├── Question1.R
│           └── Question2.R
├── grading
└── submissions
    ├── Student1-Correct-TestAssignment.Rmd
    └── Student2-Incorrect-TestAssignment.Rmd
```

All updated files [here](https://github.com/hgibling/otter-test)
Now using the automatically generated `autograder.zip`:

```
$ otter grade -p submissions -a dist/autograder/autograder.zip -o grading -v 

Launching docker containers...
Building new image using ucbdsinfra/otter-grader as base image
[+] Building 99.5s (10/10) FINISHED                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                      0.0s
 => => transferring dockerfile: 32B                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 2B                                                                                                           0.0s
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest                                                                 0.0s
 => [internal] load build context                                                                                                         0.0s
 => => transferring context: 4.75kB                                                                                                       0.0s
 => [1/6] FROM docker.io/ucbdsinfra/otter-grader                                                                                          0.0s
 => CACHED [2/6] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /va  0.0s
 => CACHED [3/6] RUN mkdir -p /autograder/source                                                                                          0.0s
 => CACHED [4/6] RUN echo ucbdsinfra/otter-grader                                                                                         0.0s
 => [5/6] ADD dist/autograder/autograder.zip /tmp/autograder.zip                                                                          0.0s
 => ERROR [6/6] RUN unzip -d /autograder/source /tmp/autograder.zip &&     cp /autograder/source/run_autograder /autograder/run_autogra  99.4s
------                                                                                                                                         
 > [6/6] RUN unzip -d /autograder/source /tmp/autograder.zip &&     cp /autograder/source/run_autograder /autograder/run_autograder &&     dos2unix /autograder/run_autograder /autograder/source/setup.sh &&     chmod +x /autograder/run_autograder &&     apt-get update && bash /autograder/source/setup.sh && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     mkdir -p /autograder/submission &&     mkdir -p /autograder/results:                                                                                                                               
#10 0.333 Archive:  /tmp/autograder.zip                                                                                                        
#10 0.333  extracting: /autograder/source/setup.sh  
#10 0.333  extracting: /autograder/source/run_otter.py  
#10 0.333  extracting: /autograder/source/requirements.txt  
#10 0.333  extracting: /autograder/source/environment.yml  
#10 0.333  extracting: /autograder/source/run_autograder  
#10 0.333  extracting: /autograder/source/requirements.r  
#10 0.333  extracting: /autograder/source/tests/Question1.R  
#10 0.334  extracting: /autograder/source/tests/Question2.R  
#10 0.334  extracting: /autograder/source/otter_config.json  
#10 0.344 dos2unix: converting file /autograder/run_autograder to Unix format...
#10 0.345 dos2unix: converting file /autograder/source/setup.sh to Unix format...
#10 0.500 Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
#10 0.695 Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
#10 0.870 Get:3 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]
#10 0.917 Get:4 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [791 kB]
#10 1.024 Get:5 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1074 kB]
#10 1.070 Get:6 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [528 kB]
#10 1.172 Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#10 1.282 Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
#10 1.392 Get:9 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
#10 1.431 Get:10 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
#10 1.439 Get:11 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
#10 1.994 Get:12 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
#10 2.060 Get:13 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1516 kB]
#10 2.089 Get:14 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [574 kB]
#10 2.099 Get:15 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1070 kB]
#10 2.163 Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.3 kB]
#10 2.164 Get:17 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [2668 B]
#10 2.164 Get:18 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [6310 B]
#10 2.755 Fetched 19.0 MB in 2s (8149 kB/s)
#10 2.755 Reading package lists...
#10 4.072 Collecting package metadata (repodata.json): ...working... done
#10 41.06 Solving environment: ...working... /autograder/source/setup.sh: line 30:   231 Killed                  conda env create -f /autograder/source/environment.yml
#10 97.81 
#10 97.81 EnvironmentLocationNotFound: Not a conda environment: /opt/conda/envs/otter-env
#10 97.81 
#10 98.02 no change     /opt/conda/condabin/conda
#10 98.02 no change     /opt/conda/bin/conda
#10 98.02 no change     /opt/conda/bin/conda-env
#10 98.02 no change     /opt/conda/bin/activate
#10 98.02 no change     /opt/conda/bin/deactivate
#10 98.02 no change     /opt/conda/etc/profile.d/conda.sh
#10 98.02 no change     /opt/conda/etc/fish/conf.d/conda.fish
#10 98.02 no change     /opt/conda/shell/condabin/Conda.psm1
#10 98.02 no change     /opt/conda/shell/condabin/conda-hook.ps1
#10 98.02 no change     /opt/conda/lib/python3.9/site-packages/xontrib/conda.xsh
#10 98.02 no change     /opt/conda/etc/profile.d/conda.csh
#10 98.02 modified      /root/.bashrc
#10 98.02 modified      /root/.zshrc
#10 98.02 modified      /root/.config/fish/config.fish
#10 98.02 modified      /root/.xonshrc
#10 98.02 modified      /root/.tcshrc
#10 98.02 
#10 98.02 ==> For changes to take effect, close and re-open your current shell. <==
#10 98.02 
#10 98.05 Cloning into '/autograder/source/ottr'...
#10 99.08 Note: switching to '9fb83dc79b7c89157b26bb42476cd7dfe285090d'.
#10 99.08 
#10 99.08 You are in 'detached HEAD' state. You can look around, make experimental
#10 99.08 changes and commit them, and you can discard any commits you make in this
#10 99.08 state without impacting any branches by switching back to a branch.
#10 99.08 
#10 99.08 If you want to create a new branch to retain commits you create, you may
#10 99.08 do so (now or later) by using -c with the switch command. Example:
#10 99.08 
#10 99.08   git switch -c <new-branch-name>
#10 99.08 
#10 99.08 Or undo this operation with:
#10 99.08 
#10 99.08   git switch -
#10 99.08 
#10 99.08 Turn off this advice by setting config variable advice.detachedHead to false
#10 99.08 
#10 99.21 
#10 99.21 EnvironmentLocationNotFound: Not a conda environment: /opt/conda/envs/otter-env
#10 99.21 
#10 99.34 
#10 99.34 EnvironmentLocationNotFound: Not a conda environment: /opt/conda/envs/otter-env
#10 99.34 
------
error: failed to solve: executor failed running [/bin/sh -c unzip -d /autograder/source /tmp/autograder.zip &&     cp /autograder/source/run_autograder /autograder/run_autograder &&     dos2unix /autograder/run_autograder /autograder/source/setup.sh &&     chmod +x /autograder/run_autograder &&     apt-get update && bash /autograder/source/setup.sh && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     mkdir -p /autograder/submission &&     mkdir -p /autograder/results]: exit code: 1
Traceback (most recent call last):
  File "/Users/hgibling/miniconda3/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/cli.py", line 127, in grade_cli
    return grade(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/__init__.py", line 66, in main
    pdfs=pdfs
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 79, in launch_grade
    img = build_image(zip_path, image, generate_hash(zip_path))
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 38, in build_image
    }, tags=[image], file=dockerfile)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 331, in build
    run(full_cmd, capture_stderr=progress is False)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/python_on_whales/utils.py", line 149, in run
    completed_process.stderr,
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/local/bin/docker buildx build --build-arg ZIPPATH=dist/autograder/autograder.zip --build-arg BASE_IMAGE=ucbdsinfra/otter-grader --file /Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/Dockerfile --tag otter-grade:c30f9155a7abb3854ddfe8fd9e5081c3 --iidfile /var/folders/vk/wtttf_1s47l2ghn62rhrsmdw0000gp/T/tmp_5dl76p9/id_file.txt .`.
It returned with code 1
The content of stdout is ''
The content of stderr can be found above the stacktrace (it wasn't captured).
```

I'm not at all familiar with docker, but I was able to get it to work with the ipynb demo files. Any suggestions?
```
Docker version 20.10.8, build 3967b7d
```

**Comment by chrispyles** [comment]
@hgibling I think I've found the issue. I've opened #392 to fix it but you can install the `fix-r-build` branch of my fork if you'd like to test it out.

```
pip uninstall -y otter-grader
pip install git+https://github.com/chrispyles/otter-grader.git@fix-r-build
```

**Comment by hgibling** [comment]
Hi @chrispyles,

I upgraded to otter-grader version 3.1.2 and reran the workflow, but it looks like I'm getting the same issue with grading:

```
Building new image using ucbdsinfra/otter-grader as base image
[+] Building 134.5s (10/10) FINISHED                                                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                                                           0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest                                                                                                                                      0.0s
 => [1/6] FROM docker.io/ucbdsinfra/otter-grader                                                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                                              0.0s
 => => transferring context: 5.04kB                                                                                                                                                                            0.0s
 => CACHED [2/6] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*                                                                0.0s
 => CACHED [3/6] RUN mkdir -p /autograder/source                                                                                                                                                               0.0s
 => CACHED [4/6] RUN echo ucbdsinfra/otter-grader                                                                                                                                                              0.0s
 => [5/6] ADD dist/autograder/autograder.zip /tmp/autograder.zip                                                                                                                                               0.0s
 => ERROR [6/6] RUN unzip -d /autograder/source /tmp/autograder.zip &&     cp /autograder/source/run_autograder /autograder/run_autograder &&     dos2unix /autograder/run_autograder /autograder/source/se  134.3s
------                                                                                                                                                                                                              
 > [6/6] RUN unzip -d /autograder/source /tmp/autograder.zip &&     cp /autograder/source/run_autograder /autograder/run_autograder &&     dos2unix /autograder/run_autograder /autograder/source/setup.sh &&     chmod +x /autograder/run_autograder &&     apt-get update && bash /autograder/source/setup.sh && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     mkdir -p /autograder/submission &&     mkdir -p /autograder/results:                                                                                                                                                                                               
#9 0.351 Archive:  /tmp/autograder.zip                                                                                                                                                                              
#9 0.351  extracting: /autograder/source/setup.sh                                                                                                                                                                   
#9 0.351  extracting: /autograder/source/run_otter.py  
#9 0.351  extracting: /autograder/source/requirements.txt  
#9 0.351  extracting: /autograder/source/environment.yml  
#9 0.351  extracting: /autograder/source/run_autograder  
#9 0.351  extracting: /autograder/source/requirements.r  
#9 0.351  extracting: /autograder/source/tests/Question1.R  
#9 0.351  extracting: /autograder/source/tests/Question2.R  
#9 0.351  extracting: /autograder/source/otter_config.json  
#9 0.364 dos2unix: converting file /autograder/run_autograder to Unix format...
#9 0.365 dos2unix: converting file /autograder/source/setup.sh to Unix format...
#9 0.515 Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
#9 0.756 Get:2 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1074 kB]
#9 0.901 Get:3 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]
#9 0.903 Get:4 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [791 kB]
#9 0.918 Get:5 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [528 kB]
#9 1.152 Get:6 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
#9 2.107 Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#9 2.326 Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
#9 2.500 Get:9 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
#9 2.505 Get:10 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
#9 2.987 Get:11 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
#9 3.050 Get:12 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
#9 4.235 Get:13 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1516 kB]
#9 4.300 Get:14 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.3 kB]
#9 4.302 Get:15 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [574 kB]
#9 4.312 Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1070 kB]
#9 4.412 Get:17 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [2668 B]
#9 4.412 Get:18 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [6310 B]
#9 4.936 Fetched 19.0 MB in 5s (4211 kB/s)
#9 4.936 Reading package lists...
#9 6.256 Collecting package metadata (repodata.json): ...working... done
#9 44.20 Solving environment: ...working... /autograder/source/setup.sh: line 36:   231 Killed                  conda env create -f /autograder/source/environment.yml
#9 133.2 
#9 133.2 EnvironmentLocationNotFound: Not a conda environment: /opt/conda/envs/otter-env
#9 133.2 
#9 133.4 no change     /opt/conda/condabin/conda
#9 133.4 no change     /opt/conda/bin/conda
#9 133.4 no change     /opt/conda/bin/conda-env
#9 133.4 no change     /opt/conda/bin/activate
#9 133.4 no change     /opt/conda/bin/deactivate
#9 133.4 no change     /opt/conda/etc/profile.d/conda.sh
#9 133.4 no change     /opt/conda/etc/fish/conf.d/conda.fish
#9 133.4 no change     /opt/conda/shell/condabin/Conda.psm1
#9 133.4 no change     /opt/conda/shell/condabin/conda-hook.ps1
#9 133.4 no change     /opt/conda/lib/python3.9/site-packages/xontrib/conda.xsh
#9 133.4 no change     /opt/conda/etc/profile.d/conda.csh
#9 133.4 modified      /root/.bashrc
#9 133.4 modified      /root/.zshrc
#9 133.4 modified      /root/.config/fish/config.fish
#9 133.4 modified      /root/.xonshrc
#9 133.4 modified      /root/.tcshrc
#9 133.4 
#9 133.4 ==> For changes to take effect, close and re-open your current shell. <==
#9 133.4 
#9 133.4 Cloning into '/autograder/source/ottr'...
#9 134.0 Note: switching to 'cec1b94d3a89b82347f60409b16b474262742568'.
#9 134.0 
#9 134.0 You are in 'detached HEAD' state. You can look around, make experimental
#9 134.0 changes and commit them, and you can discard any commits you make in this
#9 134.0 state without impacting any branches by switching back to a branch.
#9 134.0 
#9 134.0 If you want to create a new branch to retain commits you create, you may
#9 134.0 do so (now or later) by using -c with the switch command. Example:
#9 134.0 
#9 134.0   git switch -c <new-branch-name>
#9 134.0 
#9 134.0 Or undo this operation with:
#9 134.0 
#9 134.0   git switch -
#9 134.0 
#9 134.0 Turn off this advice by setting config variable advice.detachedHead to false
#9 134.0 
#9 134.1 
#9 134.1 EnvironmentLocationNotFound: Not a conda environment: /opt/conda/envs/otter-env
#9 134.1 
#9 134.2 
#9 134.2 EnvironmentLocationNotFound: Not a conda environment: /opt/conda/envs/otter-env
#9 134.2 
------
error: failed to solve: executor failed running [/bin/sh -c unzip -d /autograder/source /tmp/autograder.zip &&     cp /autograder/source/run_autograder /autograder/run_autograder &&     dos2unix /autograder/run_autograder /autograder/source/setup.sh &&     chmod +x /autograder/run_autograder &&     apt-get update && bash /autograder/source/setup.sh && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     mkdir -p /autograder/submission &&     mkdir -p /autograder/results]: exit code: 1
Traceback (most recent call last):
  File "/Users/hgibling/miniconda3/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/cli.py", line 127, in grade_cli
    return grade(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/__init__.py", line 70, in main
    network=network
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 80, in launch_grade
    img = build_image(zip_path, image, generate_hash(zip_path))
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 37, in build_image
    }, tags=[image], file=dockerfile)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 331, in build
    run(full_cmd, capture_stderr=progress is False)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/python_on_whales/utils.py", line 149, in run
    completed_process.stderr,
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/local/bin/docker buildx build --build-arg ZIPPATH=dist/autograder/autograder.zip --build-arg BASE_IMAGE=ucbdsinfra/otter-grader --file /Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/Dockerfile --tag otter-grade:f05509013956977746591052cfb954cf --iidfile /var/folders/vk/wtttf_1s47l2ghn62rhrsmdw0000gp/T/tmpb14zpgro/id_file.txt .`.
It returned with code 1
The content of stdout is ''
The content of stderr can be found above the stacktrace (it wasn't captured).
```

**Comment by chrispyles** [comment]
Did you use the commands above to upgrade, or just `pip install -U otter-grader` or the like?

**Comment by hgibling** [comment]
`fix-r-branch` didn't exist anymore, so I did:
```
pip uninstall -y otter-grader
pip install otter-grader
```

**Comment by chrispyles** [comment]
Ah OK I guess I merged the PR before you installed. You need to install from git to test this. The changes are in master now so the below should work.

```
pip uninstall -y otter-grader
pip install git+https://github.com/ucbds-infra/otter-grader
```

**Comment by hgibling** [comment]
Ok, almost there!

```
Building new image using ucbdsinfra/otter-grader as base image
[+] Building 1088.5s (11/11) FINISHED                                                                                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                                                                                           0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest                                                                                                                                      0.0s
 => [1/6] FROM docker.io/ucbdsinfra/otter-grader                                                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                                              0.0s
 => => transferring context: 5.16kB                                                                                                                                                                            0.0s
 => CACHED [2/6] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*                                                                0.0s
 => CACHED [3/6] RUN mkdir -p /autograder/source                                                                                                                                                               0.0s
 => CACHED [4/6] RUN echo ucbdsinfra/otter-grader                                                                                                                                                              0.0s
 => [5/6] ADD dist/autograder/autograder.zip /tmp/autograder.zip                                                                                                                                               0.0s
 => [6/6] RUN unzip -d /autograder/source /tmp/autograder.zip &&     cp /autograder/source/run_autograder /autograder/run_autograder &&     dos2unix /autograder/run_autograder /autograder/source/setup.s  1051.5s
 => exporting to image                                                                                                                                                                                        36.8s
 => => exporting layers                                                                                                                                                                                       36.8s
 => => writing image sha256:680ca569fcadee838856da170e5c307c9b858507803bd2174a24dd7211f6ae75                                                                                                                   0.0s 
 => => naming to docker.io/library/otter-grade:ad94e63df1243405d1f79165930c1f4e                                                                                                                                0.0s 
Traceback (most recent call last):                                                                                                                                                                                  
  File "/Users/hgibling/miniconda3/bin/otter", line 8, in <module>                                                                                                                                                  
    sys.exit(cli())
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/cli.py", line 127, in grade_cli
    return grade(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/__init__.py", line 77, in main
    output_df = merge_csv(grade_dfs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/grade/utils.py", line 38, in merge_csv
    final_dataframe = pd.concat(dataframes, axis=0, join='inner').sort_index()
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

I'm not sure what's missing. Directory structure is:
```
.
├── TestAssignment.Rmd
├── dist
│   ├── autograder
│   │   ├── TestAssignment.Rmd
│   │   ├── autograder.zip
│   │   ├── otter_config.json
│   │   ├── tests
│   │   │   ├── Question1.R
│   │   │   └── Question2.R
│   │   └── zip-contents
│   │       ├── autograder.zip
│   │       ├── environment.yml
│   │       ├── otter_config.json
│   │       ├── requirements.r
│   │       ├── requirements.txt
│   │       ├── run_autograder
│   │       ├── run_otter.py
│   │       ├── setup.sh
│   │       └── tests
│   │           ├── Question1.R
│   │           └── Question2.R
│   └── student
│       ├── TestAssignment.Rmd
│       └── tests
│           ├── Question1.R
│           └── Question2.R
├── grading
└── submissions
    ├── S1-Correct-TestAssignment.Rmd
    ├── S2-Incorrect-TestAssignment.Rmd
    └── tests
        ├── Question1.R
        └── Question2.R
```
Have updated my files [here](https://github.com/hgibling/otter-test) as well

**Comment by chrispyles** [comment]
OK I think I've found the other issue here. Once more, with feeling:

Re-install Otter from git (I've re-made the fix-r-build branch and I won't merge the PR until I hear back so this should work):

```
pip uninstall -y otter-grader
pip install git+https://github.com/chrispyles/otter-grader.git@fix-r-build
```

Then, use the same `otter grade` command _but_ add `--ext Rmd` onto the end (this tells Otter Grade it's looking for Rmd files instead of IPYNB files).

```
otter grade -p <other stuff> --ext Rmd
```

Please let me know if that works.

**Comment by hgibling** [comment]
Success! Thanks so much for debugging this with me.
