### ISSUE TITLE
How to include required files while generating an assignment?

### ISSUE THREAD

**Issue by hgibling** [ucbds-infra/otter-grader#404]
Hello,
I'm testing another assignment that requires a csv file (data.csv) to be read in to answer questions. I'm not entirely clear on how to specify the file while generating the assignment. Currently I have:
```
BEGIN ASSIGNMENT
generate: true
files: data.csv
```
in the assignment. Directory structure is (the important parts):
```
otter-test
├── assignments
│   └── A3
│       ├── A3.Rmd
│       └── data.csv
```
And I'm trying the command, while in `otter-test`:
```
otter assign assignments/A3/A3.Rmd dist/A3 --v1
```
But I'm getting the following error:
```
Generating views...
Traceback (most recent call last):
  File "/Users/hgibling/miniconda3/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/cli.py", line 43, in assign_cli
    return assign(*args, **kwargs)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/assign/__init__.py", line 59, in main
    output_nb_path = write_output_directories(master, result, assignment)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/assign/rmarkdown_adapter/output.py", line 147, in write_output_directories
    write_autograder_dir(master_rmd_path, output_rmd_path, assignment)
  File "/Users/hgibling/miniconda3/lib/python3.7/site-packages/otter/assign/rmarkdown_adapter/output.py", line 83, in write_autograder_dir
    shutil.copy(file, str(output_dir / rel_path))
  File "/Users/hgibling/miniconda3/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/hgibling/miniconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'd'
```

Should the extra files be listed in a requirements.txt? (I tried that too but got the same error.)

**Comment by chrispyles** [comment]
@hgibling `files` should be a YAML-formatted list of files. Change your assignment metadata to:

```
BEGIN ASSIGNMENT
generate: true
files:
    - data.csv
```

**Comment by hgibling** [comment]
Whoops, that was a dumb mistake. Thanks!
