### ISSUE TITLE
Otter Assign throws Unicode Decode Error!

### ISSUE THREAD

**Issue by balajialg** [ucbds-infra/otter-grader#443]
**Describe the bug**
Running otter assign in an ipynb file with Spanish translation throws the Unicode decode error listed below. 

$  otter assign lab02.ipynb dist --v1
Traceback (most recent call last):
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\la-balajialwar\AppData\Local\Python\Python310\Scripts\otter.exe\__main__.py", line 7, in <module>
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\otter\cli.py", line 43, in assign_cli
    return assign(*args, **kwargs)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\otter\assign\__init__.py", line 59, in main
    output_nb_path = write_output_directories(master, result, assignment)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\otter\assign\output.py", line 178, in write_output_directories
    write_autograder_dir(master_nb_path, output_nb_path, assignment)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\otter\assign\output.py", line 31, in write_autograder_dir
    nb = nbformat.read(f, as_version=NB_VERSION)
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\site-packages\nbformat\__init__.py", line 138, in read
    buf = fp.read()
  File "C:\Users\balajialwar\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 91853: character maps to <undefined>
Generating views...

**To Reproduce**
1. Run Otter Assign command on the lab01 and lab02 files in this [folder](https://drive.google.com/drive/u/1/folders/1IzRLWOathwvjiW9666xM1VFOc7ZcFG8v)
2. Otter assign logs the above error

**Expected behavior**
Otter Assign command should run without throwing the above error!

**Versions**
Python version: 3.10.0
Otter-Grader version: 3.1.4

**Additional context**
Using a Windows 10 machine to run the above command!

**Comment by chrispyles** [comment]
@balajialg I cannot access the drive link you shared. Requesting access.

**Comment by balajialg** [comment]
@chrispyles Provided access! Thanks

**Comment by chrispyles** [comment]
@balajialg I am not experiencing this issue running on Mac. If you have someone with a Unix machine can you ask them to run it and see if they can reproduce the error? I do not have a Windows machine to debug this with unfortunately so I'm not sure if I can help but a cursory glance at the stack trace indicates that this may in fact be an issue with nbformat rather than Otter because that package is the one actually reading the file directly and decoding the bytes.

**Comment by balajialg** [comment]
@chrispyles Let me look around and get back regarding the replication part. Thanks!

Re:nb format - if I could replicate this across other windows machines, where do I raise the issue related to nbformat?

**Comment by chrispyles** [comment]
I would open an issue on their github repo: https://github.com/jupyter/nbformat

**Comment by balajialg** [comment]
@chrispyles Sounds great! Thank you.
