### ISSUE TITLE
Error following tutorial in the doc

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#445]
**Describe the bug**
I closely followed the tutorial section  in the doc, but the following error occurred after running `otter grade`:
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/otter/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/cli.py", line 128, in grade_cli
    return grade(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/grade/__init__.py", line 58, in main
    raise ValueError(f"Invalid submission extension specified: {ext}")
ValueError: Invalid submission extension specified: None
```

**To Reproduce**
1. Download the zip file from https://otter-grader.readthedocs.io/en/latest/_static/tutorial.zip
2. `cd` into `tutorial` and run `otter assign demo.ipynb dist --v1`
3. run `otter grade -p submissions/ipynbs -a dist/autograder/autograder.zip --pdfs -v`

BTW, the doc says `otter grade -p submissions/ipynbs -a dist/autograder/demo-autograder_*.zip --pdfs -v`, which seems wrong. In Step 3, `demo-autograder_*.zip` is replaced with `autograder.zip`

**Expected behavior**
A `csv` file with points is created, as the doc says.

**Versions**
otter-grader  3.1.4

**Additional context**
The docker desktop is running. I also created my own questions (.ipynb) and ran `otter assign` and `otter grade` and encountered the same error.

**Comment by chrispyles** [comment]
This is a known issue that will be fixed with v3.2.0. For now, you can add the `--ext ipynb` flag to the `otter grade` command and it should work.

Regarding the naming of the zip file, the docs you're referencing are for the current development release of Otter v3.2.0 which isn't out yet. The docs for the current stable release can be found here: https://otter-grader.readthedocs.io/en/stable/
