### ISSUE TITLE
--- and --- in Markdown cell generate an error message

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#446]
**Describe the bug**
The following error message is generated If `---` is used twice in a Markdown cell for a question. But, files seem to be generated fine.

```
Generating views...
Generating autograder zipfile...
Generating solutions PDF...
YAML parse exception at line 1, column 0,
while scanning for the next token:
found character that cannot start any token
Traceback (most recent call last):
  File "/opt/anaconda3/envs/otter/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/otter/cli.py", line 43, in assign_cli
    return assign(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/otter/assign/__init__.py", line 113, in main
    export_notebook(
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/otter/export/__init__.py", line 33, in export_notebook
    Exporter.convert_notebook(nb_path, pdf_name, debug=debug, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/otter/export/exporters/via_latex.py", line 55, in convert_notebook
    pdf_output = pdf_exporter.from_notebook_node(nb)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/nbconvert/exporters/pdf.py", line 168, in from_notebook_node
    latex, resources = super().from_notebook_node(
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/nbconvert/exporters/latex.py", line 72, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 389, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/otter/export/exporters/templates/via_latex/index.tex.j2", line 7, in top-level template code
    ((* extends cell_style *))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/style_ipython.tex.j2", line 68, in top-level template code
    ((( text | add_prompts(first='{\color{' ~ prompt_color ~ '}' ~ prompt ~ '[{\\color{' ~ prompt_color ~ '}' ~ execution_count ~ '}]:} ', cont=indention) )))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 7, in top-level template code
    ((*- extends 'document_contents.tex.j2' -*))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 51, in top-level template code
    ((*- block figure scoped -*))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/display_priority.j2", line 5, in top-level template code
    ((*- extends 'null.j2' -*))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/null.j2", line 30, in top-level template code
    ((*- block body -*))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 206, in block 'body'
    ((( super() )))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/null.j2", line 32, in block 'body'
    ((*- block any_cell scoped -*))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/null.j2", line 85, in block 'any_cell'
    ((*- block markdowncell scoped-*)) ((*- endblock markdowncell -*))
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/otter/export/exporters/templates/via_latex/index.tex.j2", line 34, in block 'markdowncell'
    ((( super() )))
  File "/opt/anaconda3/envs/otter/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 68, in block 'markdowncell'
    ((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown+tex_math_double_backslash', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex'))))
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/nbconvert/filters/filter_links.py", line 16, in resolve_references
    return applyJSONFilters([resolve_one_reference], source)
  File "/opt/anaconda3/envs/otter/lib/python3.9/site-packages/pandocfilters.py", line 203, in applyJSONFilters
    doc = json.loads(source)
  File "/opt/anaconda3/envs/otter/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/envs/otter/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/envs/otter/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
1. Run `otter assign test.ipynb dist --v1` using the attached file.

**Expected behavior**
No error message

**Versions**
otter-grader  3.1.4
**Additional context**
None

[test.ipynb.zip](https://github.com/ucbds-infra/otter-grader/files/7490717/test.ipynb.zip)

**Comment by chrispyles** [comment]
This is not an issue with Otter but with how nbconvert/pandoc is parsing the Markdown in the notebook and converting it to LaTeX. I was not able to reproduce this error message on my machine, but I did get the same warning that you got:

````
[WARNING] Could not parse YAML metadata at line 11 column 1: :2:0: Lexical error near "```"
````

I was able to get rid of the warning by inserting a blank link between the `---` and `````:

````
# not
---
```

# instead
---

```
````

Can you try this and let me know if it works?

**Comment by spring-haru** [comment]
It worked with no warning/error message. All necessary files are created. Thank you😀
