### ISSUE TITLE
Make Docker image compatible with ARM processors

### ISSUE THREAD

**Issue by chrispyles** [ucbds-infra/otter-grader#456]
The current version of the Docker image only works with x86 processors, not ARM ones (meaning it won't work with M1 macs). This should be fixed.

I think leveraging buildx's platform options should work, accounting for the different downloads required for conda and wkhtmltopdf in the Dockerfile.

**Comment by spring-haru** [comment]
Is this related to the following error message I got in running `otter grade` for local grading using Docker?

```
Combining grades and saving...
Traceback (most recent call last):
  File "/opt/anaconda3/envs/otter/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/cli.py", line 130, in grade_cli
    return grade(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/grade/__init__.py", line 83, in main
    output_df = merge_csv(grade_dfs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/grade/utils.py", line 38, in merge_csv
    final_dataframe = pd.concat(dataframes, axis=0, join='inner').sort_index()
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/opt/anaconda3/envs/otter/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by chrispyles** [comment]
@spring-haru are you using an ARM machine? Based on the error message, I doubt it's related.

**Comment by spring-haru** [comment]
I use MacBookPro (M1) and often hear that "The Apple M1 is an ARM processor", hence I assumed it is related. I wanted to raise an issue about the error message, and thought this may be the right place to ask. Otherwise, I will raise a new issue.

**Comment by chrispyles** [comment]
Based on the error message, I don't think it's related to using an ARM processor. Are you able to successfully run the [tutorial](https://otter-grader.readthedocs.io/en/latest/tutorial.html) on your M1 machine?

**Comment by chrispyles** [comment]
I'm actually able to run the tutorial OK on my M1 machine, so I think that the issues I've been experiencing are related solely to the image build process. It seems like I'm able to run the image OK regardless of the platform it was built on. @spring-haru is this true for you as well?

**Comment by spring-haru** [comment]
Yes, the tutorial worked fine.
In fact, I created 5 assessment files, and the first three worked perfectly fine. The last two caused problems. 

(1) One file contains `np.random.default_rng(rng_seed)`, and 
(2) the other uses/imports `.csv` file.

The first three files do not have seed nor imorting file.

The above error message came from (1). The error message in my Slack message to you is from (2).

**Comment by spring-haru** [comment]
Solved. Thanks any way😄
