### ISSUE TITLE
How to make a assessment notebook for students to use in Colab

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#471]
**Describe your inquiry** 

I am looking for info on how to create an assessment that students can use in Colab. I tried to find it  in doc, but what I was able to find were metadata options, `autograder_files: []` and `colab:true` I tried them, but the notebooks created with that option generate an error message `Tests directory ./tests does not exist`. I wonder if you can tell me where I can find relevant info? I use otter-grader for local grading using Docker.

**Comment by chrispyles** [comment]
To use an Otter notebook on Colab, you must use the `colab: true` option in the assignment metadata but you must also put Otter's test cases into the Colab VM. You're seeing this error because Otter is looking for a directory called `tests` on Colab which it's not finding. Since there's no notebook file on Colab, there must be a directory of tests (which are included in the output of Otter Assign).

**Comment by py4class** [comment]
An `.ipynb` file generated by `otter assign` contains tests for each question in itself. I wonder if a directory `tests` is redundant and unnecessary.

So, I modified the following line
```
grader = otter.Notebook()
```
to
```
grader = otter.Notebook(, colab=False)
```
so that students can add their file name before `, colab=False`.

I run such an `.ipynb` file (generated by `assign`) on Colab, and `grader.check()` works fine. But the problem is that the following error occurs when `otter grade` is run in Docker
```
Launching docker containers...
Grading submissions/test-A.ipynb in container 8638dd7b205d...

EnvironmentNameNotFound: Could not find conda environment: otter-env
You can list all discoverable environments with `conda info --envs`.


Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 8, in <module>
.......
 ```
I wonder if `otter-env` is something that causes the problem.
I should be grateful if you could share your insight.

Otter-grader: 3.3.0

**Comment by chrispyles** [comment]
@py4class It looks like it might be an issue with creating the conda environment during the Docker image build. Can you paste the full output of the `otter grade` command, including the Docker build output?

**Comment by spring-haru** [comment]
I am not sure if the following is what you are after. In any case, let me paste what I see in terminal this time around:

```
╰─ otter grade -p submissions -a dist/autograder/test-autograder_2022_08_12T12_12_20_795833.zip -v --debug > otter-grade-log.txt                 ─╯
[+] Building 1.0s (14/14) FINISHED
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 854B                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                0.0s
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest                                                                      0.9s
 => [1/9] FROM docker.io/ucbdsinfra/otter-grader@sha256:9c17a8c6339e067d3fdfa67cf9cfd6a5bbfd6f8cbf15ed5ccacf1b94cd322ebe                       0.0s
 => [internal] load build context                                                                                                              0.0s
 => => transferring context: 2.59kB                                                                                                            0.0s
 => CACHED [2/9] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp  0.0s
 => CACHED [3/9] RUN mkdir -p /autograder/source                                                                                               0.0s
 => CACHED [4/9] ADD run_autograder /autograder/run_autograder                                                                                 0.0s
 => CACHED [5/9] ADD setup.sh environment.yml requirements.* /autograder/source/                                                               0.0s
 => CACHED [6/9] RUN dos2unix /autograder/run_autograder /autograder/source/setup.sh &&     chmod +x /autograder/run_autograder &&     apt-ge  0.0s
 => CACHED [7/9] ADD otter_config.json run_otter.py /autograder/source/                                                                        0.0s
 => CACHED [8/9] ADD files* /autograder/source/files/                                                                                          0.0s
 => CACHED [9/9] ADD tests /autograder/source/tests/                                                                                           0.0s
 => exporting to image                                                                                                                         0.0s
 => => exporting layers                                                                                                                        0.0s
 => => writing image sha256:a560a3a0ebdf46ed3ae160f3a0997f739bfad2ceb4df6d92c0ef9316c3079449                                                   0.0s
 => => naming to docker.io/library/otter-grade:910e3467701a4783bde7dcefa5c22a4c                                                                0.0s
Traceback (most recent call last):
  File "/Users/tetsu/opt/anaconda3/envs/otter/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/cli.py", line 130, in grade_cli
    return grade(*args, **kwargs)
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/grade/__init__.py", line 64, in main
    grade_dfs = launch_grade(autograder,
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/grade/containers.py", line 113, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/grade/containers.py", line 113, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/tetsu/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/grade/containers.py", line 189, in grade_assignments
    raise Exception(f"Executing '{submission_path}' in docker container failed! Exit code: {exit}")
Exception: Executing 'submissions/test-A.ipynb' in docker container failed! Exit code: 1

```

**Comment by spring-haru** [comment]
Somehow I used a different account `py4class` in posting the comment above. Sorry about it.

As I wrote in Slack, as a workaround, I added `ipython` to `requirements.txt` for a master `.ipynb` file which `otter assign` uses, then, the error is gone now.
