### ISSUE TITLE
Issue with running tutorial example

### ISSUE THREAD

**Issue by wang2502** [ucbds-infra/otter-grader#481]
**Describe the bug**
Not sure if others have encountered a similar issue, or it is just a special situation for me. It happens when I try to repeat the tutorial.

**To Reproduce**
When I run through the tutorial, I am able to run 'otter assign demo.ipynb dist --v1'. It was successful.
After that, I tried to run 'otter grade -p submissions/ipynbs -a dist/autograder/demo-autograder_*.zip --pdfs -v'
It produced following error:

'Launching docker containers...
Traceback (most recent call last):
  File "/home/wsy_nn/.local/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/otter/cli.py", line 130, in grade_cli
    return grade(*args, **kwargs)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/otter/grade/__init__.py", line 64, in main
    grade_dfs = launch_grade(autograder,
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/otter/grade/containers.py", line 83, in launch_grade
    img = build_image(zip_path, image, generate_hash(zip_path))
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/otter/grade/containers.py", line 33, in build_image
    if not docker.image.exists(image):
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/python_on_whales/components/image/cli_wrapper.py", line 266, in exists
    self.inspect(x)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/python_on_whales/components/image/cli_wrapper.py", line 254, in inspect
    return Image(self.client_config, x)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/python_on_whales/components/image/cli_wrapper.py", line 35, in __init__
    super().__init__(client_config, "id", reference, is_immutable_id)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/python_on_whales/client_config.py", line 162, in __init__
    self._fetch_and_parse_inspect_result(reference_or_id)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/python_on_whales/client_config.py", line 217, in _fetch_and_parse_inspect_result
    json_str = self._fetch_inspect_result_json(reference)
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/python_on_whales/components/image/cli_wrapper.py", line 44, in _fetch_inspect_result_json
    return run(self.docker_cmd + ["image", "inspect", reference])
  File "/home/wsy_nn/.local/lib/python3.9/site-packages/python_on_whales/utils.py", line 150, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker image inspect otter-grade:c3dd594a686753eee6178b196c02f7c8`.
It returned with code 1
The content of stdout is '[]
'
The content of stderr is 'Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/otter-grade:c3dd594a686753eee6178b196c02f7c8/json": dial unix /var/run/docker.sock: connect: permission denied
'

'

**Expected behavior**
I felt that it had something to do with sudo. Yet, I tried 
'sudo otter grade -p submissions/ipynbs -a dist/autograder/demo-autograder_*.zip --pdfs -v'
It would not work.

**Versions**
Python version: 3.9.7
Otter-Grader version: 3.2.1

**Comment by chrispyles** [comment]
Sorry for the delayed response. I think this is an issue with your machine (probably related to the permissions on `/var/run/docker.sock`). I had this error recently setting up a new Ubuntu machine and a quick Google got me a `chmod` (I think?) command that fixed it for me.

Closing this as it doesn't appear to be an issue related to Otter specifically. Please reopen if that's not the case.
