### ISSUE TITLE
Can't grade submissions: missing 3 required positional arguments: 'points', 'success_message', and 'failure_message'

### ISSUE THREAD

**Issue by langure** [ucbds-infra/otter-grader#493]
**Describe the bug**
When running the otter-grade command:

otter grade -p ./individual_files/ -a autograder.zip -o . -v 

The grading process starts. After reading the ipynb files, this error appear:

Launching docker containers...
Grading ./individual_files/submission.ipynb in container ee2ffb4b5abd...
Traceback (most recent call last):
  File "/home/user/venv/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/home/user/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/venv/lib/python3.10/site-packages/otter/cli.py", line 130, in grade_cli
    return grade(*args, **kwargs)
  File "/home/user/venv/lib/python3.10/site-packages/otter/grade/__init__.py", line 64, in main
    grade_dfs = launch_grade(autograder,
  File "/home/user/venv/lib/python3.10/site-packages/otter/grade/containers.py", line 113, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "/home/user/venv/lib/python3.10/site-packages/otter/grade/containers.py", line 113, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/venv/lib/python3.10/site-packages/otter/grade/containers.py", line 192, in grade_assignments
    scores = pickle.load(f)
TypeError: TestCase.__new__() missing 3 required positional arguments: 'points', 'success_message', and 'failure_message'

**To Reproduce**
1. Get the required files: the ipynb file and autograder.zip
2. Run the command otter grade -p ./individual_files/ -a autograder.zip -o . -v 
3. See error

**Expected behavior**
The csv file with the grades should be generated.

**Versions**
Python 3.10
Otter 3.3.0
Using latest Docker from Docker Hub.

**Additional context**
As for two weeks before, it was correctly working but now it's broken.

**Comment by chrispyles** [comment]
This issue seems like it might be caused by an outdated version of the Otter Docker image. What is the tag and image id that you have? You should be able to find this with `docker image ls` and look for the most recent image with the name `ucbdsinfra/otter-grader`.

**Comment by langure** [comment]
Hello, here are the tags.

otter-grade               9df11660328b6354656a235e4374bee6   d0d09b9839bd   22 hours ago   6.76GB
<none>                    <none>                             3b56103b4781   2 weeks ago    6.76GB
otter-grade               9d34db2682851e07d48b6c93ea1669dd   954d0c6fcdc9   2 weeks ago    6.76GB

Thanks!

**Comment by chrispyles** [comment]
Those images are the ones created by Otter to grade individual assignments. Can you send the details for images that are called `ucbdsinfra/otter-grader` (not `otter-grade`)?

**Comment by langure** [comment]
Sure

ucbdsinfra/otter-grader   latest                             d1be0d7564b3   4 months ago   4.77GB

I finally made it work with:

pip install otter-grader==2.0.0
otter grade -p ./individual_files/ -a autograder.zip -o . -v --image ucbdsinfra/otter-grader:2.2.4

But any other combination would yield that error. My first attempt was done with both latest versions (the image and the otter-grader module)

**Comment by chrispyles** [comment]
Yeah I think the issue is that the Docker image is out of date. Can you try pulling the latest version of the image (`docker pull ucbdsinfra/otter-grader`), ensuring you have the latest version of Otter (3.3.0), and running again?

**Comment by langure** [comment]
Hello, same issue:

 pip install otter-grader (get latest)

docker image ls
ucbdsinfra/otter-grader   latest                             92d635eac984   2 weeks ago     4.72GB

Traceback (most recent call last):
  File "/home/manager/.local/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/home/manager/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/manager/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/manager/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/manager/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/manager/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/manager/.local/lib/python3.8/site-packages/otter/cli.py", line 130, in grade_cli
    return grade(*args, **kwargs)
  File "/home/manager/.local/lib/python3.8/site-packages/otter/grade/__init__.py", line 64, in main
    grade_dfs = launch_grade(autograder,
  File "/home/manager/.local/lib/python3.8/site-packages/otter/grade/containers.py", line 113, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "/home/manager/.local/lib/python3.8/site-packages/otter/grade/containers.py", line 113, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/manager/.local/lib/python3.8/site-packages/otter/grade/containers.py", line 192, in grade_assignments
    scores = pickle.load(f)
TypeError: __new__() missing 3 required positional arguments: 'points', 'success_message', and 'failure_message'

**Comment by chrispyles** [comment]
You need to use the `docker pull` command I specified in my last response, no `pip`. The digest of the latest tag of the image is f13f6b35c5c6 (i.e. this should be shown in `docker image ls` once you've correctly pulled the latest version of the image).

**Comment by chrispyles** [comment]
Closing this since there's been no response but if there's still an issue please feel free to reopen.
