### ISSUE TITLE
Otter Grade --ext Rmd throw error (python_on_whales.exceptions.DockerException:)

### ISSUE THREAD

**Issue by sukhjitsehra** [ucbds-infra/otter-grader#526]
**Describe the bug**
I am using otter grader to create autograded Rmd files for Gradescope. When I run otter run command locally to test, all tests are succeeded and grades are displayed. But I run otter run grade it is throwing error. I have tried on different machines (Windows and Mac) and with otter (latest version) as well as older version 3.2 for creating the autograder file (Version V0), but error same as given below.

**To Reproduce**
1. Went to autograder folder that has all the files to run the command otter grade, and after some time of execution, it throws the following error:

RROR: failed to solve: executor failed running [/bin/sh -c dos2unix /autograder/run_autograder /autograder/source/setup.sh &&     chmod +x /autograder/run_autograder &&     apt-get update && bash /autograder/source/setup.sh && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     mkdir -p /autograder/submission &&     mkdir -p /autograder/results]: exit code: 1
Traceback (most recent call last):
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/otter/cli.py", line 154, in grade_cli
    g = grade(*args, **kwargs)
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/otter/grade/__init__.py", line 78, in main
    grade_dfs = launch_grade(autograder,
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/otter/grade/containers.py", line 87, in launch_grade
    img = build_image(zip_path, image, generate_hash(zip_path))
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/otter/grade/containers.py", line 47, in build_image
    docker.build(tmp_dir, build_args={
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 373, in build
    run(full_cmd, capture_stderr=progress is False)
  File "/Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/local/bin/docker buildx build --build-arg BASE_IMAGE=ucbdsinfra/otter-grader --load --file /Volumes/data/SystemSoftwares/anaconda3/envs/r_40/lib/python3.10/site-packages/otter/grade/Dockerfile --tag otter-grade:f2a5bbec5765ef6c5bbf08d0b97c1ead --iidfile /var/folders/ms/dpdb09zd1k55h9q7t_ph07840000gq/T/tmpiu9xe1jt/id_file.txt /var/folders/ms/dpdb09zd1k55h9q7t_ph07840000gq/T/tmp9_3dc0pf`.
It returned with code 1
The content of stdout is ''
The content of stderr can be found above the stacktrace (it wasn't captured).

**Expected behavior**
To run all the test local and grade assignment by creating grades file

**Versions**
Python version:  3.10.1
Otter-grader version: 4.0.1
Docker version 20.10.17, build 100c701

**Additional context**

**Comment by chrispyles** [comment]
@sukhjitsehra this looks like an error with conda attempting to solve the environment while installing dependencies. Are you using a custom environment.yml, requirements.txt, or requirements.r file?
