### ISSUE TITLE
MissingIDFieldWarning

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#553]
**Describe the bug**
When running otter assign or the cli tool for converting v0 notebooks to v1 with otter version 4.1.0 I get an error detailing a missing id field warning. otter assign creates the autograder/x.ipynb notebook but not the autograder.zip nor any of the other expected autograder files. The notebook does not appear to be missing an id field in any cell. I ran nbformat.validate with no warning as well as nbformat.validator.normalize -- no changes.

**To Reproduce**
1. python3 -m otter.assign.v0.convert lab01.ipynb lab01-v1.ipynb
2. The following Warning occurs: 
| MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want | to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are 
| fixing this issue transparently, and will stop doing so in the future.
| validate(nb)
3. Run from python3 shell:
``` 
import nbformat
note = nbformat.read("lab01.ipynb")
nbformat.validate(note) # nothing comes back
note_tuple = nbformat.validator.normalize(note)
note_tuple[0] --> 0. # meaning no changes
```
4. If I execute otter assign on the v1 notebook generated by cli tool with the warning:
     `python3 -m otter assign lab01-v1.ipynb dist`
--> I end up with the following error(Full Stacktrace below):
```  
File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 23, column 1:
    :q
    ^
could not find expected ':'
  in "<unicode string>", line 24, column 1:
    q
```
6. I also tried executing otter assign on the v0 notebook: 
     `python3 otter assign lab01.ipynb dist`
    The appropriate folders(student and autograder) as well as the notebooks are created but the autograder directory does not have any supporting files -- autograder.zip, lab01-sol.ipynb, etc
The same MissingIdFieldWarning occurs as it did using the cli convert tool.

**Expected behavior**
The conversion to a v1 notebook should generate the new notebook(or possibly list the problems that are stopping it from working.) and then otter assign should work as intended.

**Versions**
otter-grader: 4.1.0
python: 3.8.2

**Additional context**
Here is the full stack trace promised from above:
```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/__main__.py", line 7, in <module>
    cli()
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/cli.py", line 65, in assign_cli
    return assign(*args, **kwargs)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/assign/__init__.py", line 59, in main
    write_output_directories(assignment)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/assign/output.py", line 105, in write_output_directories
    transformed_nb = nb_transformer.transform_notebook(nb)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/assign/notebook_transformer.py", line 102, in transform_notebook
    transformed_cells = self._get_transformed_cells(nb['cells'])
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/assign/notebook_transformer.py", line 160, in _get_transformed_cells
    self.assignment.update(get_cell_config(cell))
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/otter/assign/blocks.py", line 80, in get_cell_config
    config = yaml.full_load("\n".join(source))
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/__init__.py", line 105, in full_load
    return load(stream, FullLoader)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/Users/sean/Desktop/sp22/venv/lib/python3.8/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 23, column 1:
    :q
    ^
could not find expected ':'
  in "<unicode string>", line 24, column 1:
    q
```

**Comment by sean-morris** [comment]
Ok so for reasons, I don't quite get yet, if I change the nbformat_minor to 4 -- it was 5 -- everything works!

**Comment by chrispyles** [comment]
I think the YAML error you're getting is because there's invalid YAML in the `BEGIN ASSIGNMENT` cell.

<img width="1373" alt="Screen Shot 2022-10-12 at 9 51 46 PM" src="https://user-images.githubusercontent.com/40970945/195504687-134d2e2b-94d0-4de1-ad28-26895dfdfdc4.png">

For the `MissingIDFieldWarning`, this is because Otter removes cell IDs from all notebooks it produces due to issues we were having when the cell IDs were originally added to the jupyter notebook format. I'll leave this issue open to track the removal of that code to leave the cell IDs in (maybe using the specified `normalize` function?).

**Comment by sean-morris** [comment]
Thanks Chris. Got it.
