### ISSUE TITLE
`ottr` sometimes fails when `=` is used for assignment

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#579]
I don't have an MRE for this so not sure how useful it is, but I have noticed that `ottr` sometimes fails when `=` is used for assignment instead of `<-` in R. This is the error message:

```
Traceback (most recent call last):
  File "/home/joel/miniconda3/envs/531-test/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/otter/cli.py", line 173, in run_cli
    return run(*args, **kwargs)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/otter/run/__init__.py", line 59, in main
    run_autograder_main(ag_dir, logo=logo, debug=debug)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/otter/run/run_autograder/__init__.py", line 65, in main
    scores = runner.run()
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/otter/run/run_autograder/runners/r_runner.py", line 209, in run
    output = R_PACKAGES["ottr"].run_autograder(
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/rpy2/robjects/functions.py", line 201, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/rpy2/robjects/functions.py", line 124, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/joel/miniconda3/envs/531-test/lib/python3.10/site-packages/rpy2/rinterface.py", line 810, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in right_expr[[1]] : object of type 'symbol' is not subsettable
```

**Comment by chrispyles** [comment]
This is a known issue that is fixed by #506, which will be included in the next release of ottr (although I'm not sure when that will be).
