### ISSUE TITLE
Does otter-grader work with sympy?

### ISSUE THREAD

**Issue by jake-bobowski** [ucbds-infra/otter-grader#615]
I've tried to create a very simple Jupyter Notebook with a single symbolic question to be graded using Otter-Grader.  Here is the complete configuration file:

![image](https://user-images.githubusercontent.com/82606543/223324053-6c4926c9-e5de-460e-aa52-48add5918f1a.png)

The screenshot above shows that the test:

```python
y == x
```

results in

```python 
True
```

Running the 'otter assign' command does not report any errors.

However, I can't get Otter-Grader to grade this problem correctly.  

Here's an attempt to complete and submit a student notebook:

![image](https://user-images.githubusercontent.com/82606543/223324185-a282279d-6636-42a5-a248-f5f301c3c858.png)

As shown above, the test now fails.  Running the 'otter grade' command is fine (no errors are reported), but it assigns a grade of zero for the single auto-graded question.

My questions are:

 - Does Otter-Grader support sympy questions?
 - If it does, what am doing wrong in the above example?

Thanks in advance for your help!

Jake
@Jaymes92 @jake-bobowski

**Comment by chrispyles** [comment]
Hi @jake-bobowski, otter should be compatible with sympy questions. What versions of otter and sympy are you using? I recreated your example on my machine and it ran successfully.

**Comment by jake-bobowski** [comment]
Hi @chrispyles, thanks for following up.  It's good to hear that it should run successfully.  I'm running version 4.2.1 of otter-grader and version 1.11.1 of sympy.

**Comment by chrispyles** [comment]
@jake-bobowski I have installed the versions you listed on my machine and it is still running fine. Can you do the following:

1) Re-run `otter assign` to generate the autograder zip file
2) In the autograder zip file, edit `otter_config.json` to have `"debug": true`
3) Re-zip the zip file contents with these changes
4) Run `otter grade` with this new autograder zip file and the `-vv` flag

and send whatever's printed to the console?

**Comment by jake-bobowski** [comment]
Thanks @chrispyles, I tried following the instructions you sent.  Here's what was printed in the console:

[INFO otter.grade.main] Launching Docker containers
[INFO otter.grade.main] Combining grades and saving
Traceback (most recent call last):
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jbobowsk\venv\grading\Scripts\otter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\cli.py", line 154, in grade_cli
    g = grade(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\__init__.py", line 94, in main
    output_df = merge_csv(grade_dfs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\utils.py", line 38, in merge_csv
    final_dataframe = pd.concat(dataframes, axis=0, join='inner').sort_index()
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\pandas\util\_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\pandas\core\reshape\concat.py", line 369, in concat
    op = _Concatenator(
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\pandas\core\reshape\concat.py", line 426, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

When I use the -vz flag instead of -vv, the console output is:

[INFO otter.grade.main] Launching Docker containers
[INFO otter.grade.containers.grade_assignments] Grading .\submissions\OtterSympy_2023_07_22T21_35_11_725671.zip in container 6897c74d953f...
Traceback (most recent call last):
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jbobowsk\venv\grading\Scripts\otter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\cli.py", line 154, in grade_cli
    g = grade(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\__init__.py", line 78, in main
    grade_dfs = launch_grade(autograder,
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\containers.py", line 115, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\containers.py", line 115, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\containers.py", line 187, in grade_assignments
    raise Exception(f"Executing '{submission_path}' in docker container failed! Exit code: {exit}")
Exception: Executing '.\submissions\OtterSympy_2023_07_22T21_35_11_725671.zip' in docker container failed! Exit code: 1

**Comment by chrispyles** [comment]
@jake-bobowski Are you sure you used `-vv` in the first example? There should be some DEBUG logs but I only see INFO logs (only INFO logs comes from using `-v` instead of `-vv`). Please use `-vv` and `-z`. If you're not getting debug logs with those, try separating out the `v`s (`-v -v -z`).

**Comment by jake-bobowski** [comment]
Hi @chrispyles:

Here's what I have inside otter_config.json:

{
  "zips": true,
  "lang": "python",
  "debug": true
}

and here's the output printed to the terminal.  I've included also the "otter grade" command:

PS D:\UBCO\2022-2023\Teaching\PHYS 121\Jupyter Labs\Otter Sympy Test\ChrisPyles test> otter grade -a .\dist\autograder\OtterSympy-autograder_2023_07_22T21_33_57_462756.zip -p .\submissions\ -v -v -z
[INFO otter.grade.main] Launching Docker containers
[INFO otter.grade.containers.grade_assignments] Grading .\submissions\OtterSympy_2023_07_22T21_35_11_725671.zip in container b7fa07dc81f8...
[DEBUG otter.grade.containers.grade_assignments] Container b7fa07dc81f8 logs:
    ‏
      _________        __          __
     /  _____  \    __|  |__    __|  |__
    |  /     \  |  |__    __|  |__    __|   _______    _  _____
    | |       | |     |  |        |  |     |  ___  |  | |/ ____|
    | |       | |     |  |        |  |     | |___| |  |   /
    | |       | |     |  |        |  |     | ______|  |  |
    |  \_____/  |     |  |_       |  |_    | |_____   |  |
     \_________/       \ __|       \ __|    \______|  |__|
                                                    v4.2.1


    Traceback (most recent call last):
      File "/autograder/source/run_otter.py", line 11, in <module>
        run_autograder('/autograder')
      File "/opt/conda/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/__init__.py", line 65, in main
        scores = runner.run()
      File "/opt/conda/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/runners/python_runner.py", line 137, in run
        script = os.path.splitext(subm_path)[1] == ".py",
      File "/opt/conda/envs/otter-env/lib/python3.7/site-packages/otter/execute/__init__.py", line 73, in grade_notebook
        seed=seed, seed_variable=seed_variable)
      File "/opt/conda/envs/otter-env/lib/python3.7/site-packages/otter/execute/execute_notebook.py", line 110, in execute_notebook
        exec(cell_source, global_env)
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'sympy'

Traceback (most recent call last):
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jbobowsk\venv\grading\Scripts\otter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\cli.py", line 154, in grade_cli
    g = grade(*args, **kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\__init__.py", line 78, in main
    grade_dfs = launch_grade(autograder,
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\containers.py", line 115, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\containers.py", line 115, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jbobowsk\venv\grading\lib\site-packages\otter\grade\containers.py", line 187, in grade_assignments
    raise Exception(f"Executing '{submission_path}' in docker container failed! Exit code: {exit}")
Exception: Executing '.\submissions\OtterSympy_2023_07_22T21_35_11_725671.zip' in docker container failed! Exit code: 1





If I run the "otter grader" command without the "debug": true option, I get the output below.  The command execetutes without errors, but it grades the submission as incorrect.  When I run 'grader.check("q1.1")' in the actual Jupyter notebook, it says that it's correct:

(grading) PS D:\UBCO\2022-2023\Teaching\PHYS 121\Jupyter Labs\Otter Sympy Test\ChrisPyles test> otter grade -a .\dist\autograder\OtterSympy-autograder_2023_07_22T21_33_57_462756.zip -p .\submissions\ -v -v -z
[INFO otter.grade.main] Launching Docker containers
[INFO otter.grade.containers.build_image] Building new image using ucbdsinfra/otter-grader as base image
[INFO otter.grade.containers.grade_assignments] Grading .\submissions\OtterSympy_2023_07_22T21_35_11_725671.zip in container 28fb99f2d0b2...
[DEBUG otter.grade.containers.grade_assignments] Container 28fb99f2d0b2 logs:
    ‏
      _________        __          __
     /  _____  \    __|  |__    __|  |__
    |  /     \  |  |__    __|  |__    __|   _______    _  _____
    | |       | |     |  |        |  |     |  ___  |  | |/ ____|
    | |       | |     |  |        |  |     | |___| |  |   /
    | |       | |     |  |        |  |     | ______|  |  |
    |  \_____/  |     |  |_       |  |_    | |_____   |  |
     \_________/       \ __|       \ __|    \______|  |__|
                                                    v4.2.1






    ------------------------------- GRADING SUMMARY --------------------------------

    Error encountered while trying to verify scores with log:
    'bool' object has no attribute 'test_case'


    Total Score: 0.000 / 1.000 (0.000%)

               name  score  max_score
    0  Public Tests    NaN        NaN
    1          q1.1    0.0        1.0

[INFO otter.grade.main] Combining grades and saving

**Comment by chrispyles** [comment]
> ModuleNotFoundError: No module named 'sympy'

It looks like the grading image you've created doesn't have sympy installed. Can you add

```yaml
requirements:
  - sympy
```

in your assignment config, rerun otter assign, and use the resulting autograder zip with otter grade (continuing to use the flags from above)?

**Comment by jake-bobowski** [comment]
Thanks.  I'll give it a try, but the 'grading' environment does have sympy installed:

```
(grading) PS C:\Users\jbobowsk\venv\grading> pip install sympy
Requirement already satisfied: sympy in c:\users\jbobowsk\venv\grading\lib\site-packages (1.11.1)
Requirement already satisfied: mpmath>=0.19 in c:\users\jbobowsk\venv\grading\lib\site-packages (from sympy) (1.2.1)

[notice] A new release of pip available: 22.2.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(grading) PS C:\Users\jbobowsk\venv\grading>
```

**Comment by jake-bobowski** [comment]
Hi @chrispyles:

Adding
```python
requirements:
  - sympy
```
to # ASSIGNMENT CONFIG cell seems to have fixed the problem!  The question is now marked as correct.  Here's what the 'otter grade' command output to the terminal:

```
(grading) PS D:\UBCO\2022-2023\Teaching\PHYS 121\Jupyter Labs\Otter Sympy Test\ChrisPyles test> otter grade -a .\dist\autograder\OtterSympy-autograder_2023_07_25T07_13_10_100517.zip -p .\submissions\ -v -v -z
[INFO otter.grade.main] Launching Docker containers
[INFO otter.grade.containers.build_image] Building new image using ucbdsinfra/otter-grader as base image
[INFO otter.grade.containers.grade_assignments] Grading .\submissions\OtterSympy_2023_07_25T07_14_38_969140.zip in container edfd9ad6a044...
[DEBUG otter.grade.containers.grade_assignments] Container edfd9ad6a044 logs:
    ‏
      _________        __          __
     /  _____  \    __|  |__    __|  |__
    |  /     \  |  |__    __|  |__    __|   _______    _  _____
    | |       | |     |  |        |  |     |  ___  |  | |/ ____|
    | |       | |     |  |        |  |     | |___| |  |   /
    | |       | |     |  |        |  |     | ______|  |  |
    |  \_____/  |     |  |_       |  |_    | |_____   |  |
     \_________/       \ __|       \ __|    \______|  |__|
                                                    v4.0.2






    ------------------------------- GRADING SUMMARY --------------------------------

    Error encountered while trying to verify scores with log:
    'TestCaseResult' object has no attribute 'hidden'


    Total Score: 1.000 / 1.000 (100.000%)

               name  score  max_score
    0  Public Tests    NaN        NaN
    1          q1.1    1.0        1.0

[INFO otter.grade.main] Combining grades and saving
```
Is it odd that
```python
requirements:
    - sympy
 ```
is needed when sympy is already part of the 'grading' environment?  Thanks so much for all of your help!

**Comment by chrispyles** [comment]
sympy may be installed in your local conda environment, but it still needs to be specified so that Otter knows to install it in the environment it creates inside the docker container it uses to grade the notebook. You can see what Otter installs by default in the docker container [here](https://otter-grader.readthedocs.io/en/latest/workflow/otter_generate/container_image.html). Anything not listed here needs to be explicitly specified.
