### ISSUE TITLE
Error running tests in export cell

### ISSUE THREAD

**Issue by bdsomer** [ucbds-infra/otter-grader#678]
**Describe the bug**
When trying to run the export cell of a notebook generated using `otter assign`, I get the following output and error:
```
Running your submission against local test cases...


Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".../lib/python3.11/site-packages/otter/check/validate_export/__main__.py", line 45, in <module>
    main()
  File ".../lib/python3.11/site-packages/otter/check/validate_export/__main__.py", line 31, in main
    results = grade_notebook(
              ^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/otter/execute/__init__.py", line 85, in grade_notebook
    gp = GradingPreprocessor(config=c)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/nbconvert/preprocessors/base.py", line 42, in __init__
    super().__init__(**kw)
  File ".../lib/python3.11/site-packages/nbconvert/utils/base.py", line 40, in __init__
    super().__init__(**kw)
  File ".../lib/python3.11/site-packages/traitlets/config/configurable.py", line 110, in __init__
    self.config = config
    ^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 729, in __set__
    self.set(obj, value)
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 718, in set
    obj._notify_trait(self.name, old_value, new_value)
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1501, in _notify_trait
    self.notify_change(
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1513, in notify_change
    return self._notify_observers(change)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1560, in _notify_observers
    c(event)
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1142, in compatible_observer
    return func(self, change)
           ^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/traitlets/config/configurable.py", line 219, in _config_changed
    self._load_config(change.new, traits=traits, section_names=section_names)
  File ".../lib/python3.11/site-packages/traitlets/config/configurable.py", line 182, in _load_config
    setattr(self, name, deepcopy(config_value))
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 729, in __set__
    self.set(obj, value)
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 703, in set
    new_value = self._validate(obj, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 735, in _validate
    value = self.validate(obj, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 2532, in validate
    self.error(obj, value)
  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 841, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'test_dir' trait of a GradingPreprocessor instance expected a unicode string, not the NoneType None.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 2
      1 # Save your notebook first, then run this cell to export your submission.
----> 2 grader.export(pdf=False, run_tests=True)

File .../lib/python3.11/site-packages/otter/check/utils.py:157, in grading_mode_disabled(wrapped, self, args, kwargs)
    155 if type(self)._grading_mode:
    156     return
--> 157 return wrapped(*args, **kwargs)

File .../lib/python3.11/site-packages/otter/check/utils.py:144, in incompatible_with.<locals>.incompatible(wrapped, self, args, kwargs)
    142     else:
    143         return
--> 144 return wrapped(*args, **kwargs)

File .../lib/python3.11/site-packages/otter/check/utils.py:194, in logs_event.<locals>.event_logger(wrapped, self, args, kwargs)
    192 except Exception as e:
    193     self._log_event(event_type, success=False, error=e)
--> 194     raise e
    196 else:
    197     self._log_event(event_type, results=results, question=question, shelve_env=shelve_env)

File .../lib/python3.11/site-packages/otter/check/utils.py:188, in logs_event.<locals>.event_logger(wrapped, self, args, kwargs)
    185     question, results, shelve_env = wrapped(*args, **kwargs)
    187 else:
--> 188     results = wrapped(*args, **kwargs)
    189     shelve_env = {}
    190     question = None

File .../lib/python3.11/site-packages/otter/check/notebook.py:403, in Notebook.export(self, nb_path, export_path, pdf, filtering, pagebreaks, files, display_link, force_save, run_tests)
    401 if run_tests:
    402     print("Running your submission against local test cases...\n")
--> 403     results = grade_zip_file(zip_path, nb_path, self._path)
    404     print(
    405         "Your submission received the following results when run against " + \
    406         "available test cases:\n\n" + indent(results.summary(), "    "))
    408 if display_link:
    409     # create and display output HTML

File .../lib/python3.11/site-packages/otter/check/utils.py:82, in grade_zip_file(zip_path, nb_arcname, tests_dir)
     79 print(results.stderr.decode("utf-8"))
     81 if results.stderr:
---> 82     raise RuntimeError(results.stderr)
     84 with open(results_path, "rb") as f:
     85     results = dill.load(f)

RuntimeError: b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File ".../lib/python3.11/site-packages/otter/check/validate_export/__main__.py", line 45, in <module>\n    main()\n  File ".../lib/python3.11/site-packages/otter/check/validate_export/__main__.py", line 31, in main\n    results = grade_notebook(\n              ^^^^^^^^^^^^^^^\n  File ".../lib/python3.11/site-packages/otter/execute/__init__.py", line 85, in grade_notebook\n    gp = GradingPreprocessor(config=c)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File ".../lib/python3.11/site-packages/nbconvert/preprocessors/base.py", line 42, in __init__\n    super().__init__(**kw)\n  File ".../lib/python3.11/site-packages/nbconvert/utils/base.py", line 40, in __init__\n    super().__init__(**kw)\n  File ".../lib/python3.11/site-packages/traitlets/config/configurable.py", line 110, in __init__\n    self.config = config\n    ^^^^^^^^^^^\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 729, in __set__\n    self.set(obj, value)\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 718, in set\n    obj._notify_trait(self.name, old_value, new_value)\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1501, in _notify_trait\n    self.notify_change(\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1513, in notify_change\n    return self._notify_observers(change)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1560, in _notify_observers\n    c(event)\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 1142, in compatible_observer\n    return func(self, change)\n           ^^^^^^^^^^^^^^^^^^\n  File ".../lib/python3.11/site-packages/traitlets/config/configurable.py", line 219, in _config_changed\n    self._load_config(change.new, traits=traits, section_names=section_names)\n  File ".../lib/python3.11/site-packages/traitlets/config/configurable.py", line 182, in _load_config\n    setattr(self, name, deepcopy(config_value))\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 729, in __set__\n    self.set(obj, value)\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 703, in set\n    new_value = self._validate(obj, value)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 735, in _validate\n    value = self.validate(obj, value)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 2532, in validate\n    self.error(obj, value)\n  File ".../lib/python3.11/site-packages/traitlets/traitlets.py", line 841, in error\n    raise TraitError(e)\ntraitlets.traitlets.TraitError: The \'test_dir\' trait of a GradingPreprocessor instance expected a unicode string, not the NoneType None.\n'
```

**To Reproduce**
Create a simple notebook with a question that has a test, like so:
```
{
 "cells": [
  {
   "cell_type": "raw",
   "id": "674ecf9b",
   "metadata": {},
   "source": [
    "# ASSIGNMENT CONFIG\n",
    "export_cell:\n",
    "    pdf: false"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7b205b0b",
   "metadata": {},
   "source": [
    "# Example Test"
   ]
  },
  {
   "cell_type": "raw",
   "id": "ac2958b0",
   "metadata": {},
   "source": [
    "# BEGIN QUESTION\n",
    "name: q1"
   ]
  },
  {
   "cell_type": "raw",
   "id": "1fdf7774",
   "metadata": {},
   "source": [
    "# BEGIN SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9f18a9ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hello world\n"
     ]
    }
   ],
   "source": [
    "print('hello world')"
   ]
  },
  {
   "cell_type": "raw",
   "id": "48d1ffa3",
   "metadata": {},
   "source": [
    "# END SOLUTION"
   ]
  },
  {
   "cell_type": "raw",
   "id": "5b509cca",
   "metadata": {},
   "source": [
    "# BEGIN TESTS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a5ad319f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "True"
   ]
  },
  {
   "cell_type": "raw",
   "id": "d7690fb8",
   "metadata": {},
   "source": [
    "# END TESTS"
   ]
  },
  {
   "cell_type": "raw",
   "id": "a60f8819",
   "metadata": {},
   "source": [
    "# END QUESTION"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

Then, open this notebook and run through all of the cells. Upon running the export cell, the aforementioned error occurs.

**Expected behavior**
The export cell runs successfully.

**Versions**
Python 3.11.4, Otter 5.0.1

**Additional context**
The issue does not occur when using Otter 4.4.1 to run the notebook, independent of the Otter version used to assign the notebook. The issue does occur when using Otter 5.0.0 or Otter 5.0.1 to run the notebook.

**Comment by chrispyles** [comment]
This should be fixed in v5.0.2
