### ISSUE TITLE
Fix pdfkit, pypdf, matplotlib dependencies

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#688]
I installed otter 5.0.2 in a near-virgin unix environment  and ran the tutorial. Running otter assign on the demo.ipynb file produced error messages that called for pdfkit and pypdf to be installed, along with several warning messages. Likewise, when running the tutorial's demo.ipynb in JupyterHub, an error message was produced calling for matplotlib to be installed. Installing these packages fixed the issue, though the warning messages remain. Running python 3.11.4. Transcript follows.

```
(otter-env) instructor@jupyter-lc126:~$ cd tutorial
(otter-env) instructor@jupyter-lc126:~/tutorial$ otter assign demo.ipynb dist
/opt/conda/envs/otter-env/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/opt/conda/envs/otter-env/bin/otter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/cli.py", line 64, in assign_cli
    return assign(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/assign/__init__.py", line 95, in main
    export_notebook(
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/export/__init__.py", line 42, in export_notebook
    Exporter.convert_notebook(nb_path, pdf_name, **kwargs)
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/export/exporters/via_html.py", line 36, in convert_notebook
    import pdfkit
ModuleNotFoundError: No module named 'pdfkit'
(otter-env) instructor@jupyter-lc126:~/tutorial$ otter --version
/opt/conda/envs/otter-env/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
  _________        __          __
 /  _____  \    __|  |__    __|  |__
|  /     \  |  |__    __|  |__    __|   _______    _  _____
| |       | |     |  |        |  |     |  ___  |  | |/ ____|
| |       | |     |  |        |  |     | |___| |  |   /
| |       | |     |  |        |  |     | ______|  |  |
|  \_____/  |     |  |_       |  |_    | |_____   |  |
 \_________/       \ __|       \ __|    \______|  |__|
                                                v5.0.2

Python version: 3.11.4
Otter-Grader version: 5.0.2
(otter-env) instructor@jupyter-lc126:~/tutorial$ conda install -n otter-env pdfkit
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): - Killed
(otter-env) instructor@jupyter-lc126:~/tutorial$ pip install pdfkit
Collecting pdfkit
  Downloading pdfkit-1.0.0-py3-none-any.whl (12 kB)
Installing collected packages: pdfkit
Successfully installed pdfkit-1.0.0
(otter-env) instructor@jupyter-lc126:~/tutorial$ otter assign demo.ipynb dist
/opt/conda/envs/otter-env/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/opt/conda/envs/otter-env/bin/otter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/cli.py", line 64, in assign_cli
    return assign(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/assign/__init__.py", line 95, in main
    export_notebook(
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/export/__init__.py", line 42, in export_notebook
    Exporter.convert_notebook(nb_path, pdf_name, **kwargs)
  File "/opt/conda/envs/otter-env/lib/python3.11/site-packages/otter/export/exporters/via_html.py", line 37, in convert_notebook
    from pypdf import PdfMerger
ModuleNotFoundError: No module named 'pypdf'
(otter-env) instructor@jupyter-lc126:~/tutorial$ conda install -n otter-env pypdy
^[[A^[[B^C
CondaError: KeyboardInterrupt

(otter-env) instructor@jupyter-lc126:~/tutorial$ conda install -n otter-env pypdf
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.7.2

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.2



## Package Plan ##

  environment location: /opt/conda/envs/otter-env

  added / updated specs:
    - pypdf


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    dataclasses-0.8            |     pyhc8e2a94_3          10 KB  conda-forge
    pypdf-3.14.0               |     pyhd8ed1ab_0         207 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         216 KB

The following NEW packages will be INSTALLED:

  dataclasses        conda-forge/noarch::dataclasses-0.8-pyhc8e2a94_3
  pypdf              conda-forge/noarch::pypdf-3.14.0-pyhd8ed1ab_0


Proceed ([y]/n)?


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(otter-env) instructor@jupyter-lc126:~/tutorial$ otter assign demo.ipynb dist
/opt/conda/envs/otter-env/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(otter-env) instructor@jupyter-lc126:~/tutorial$
```

**Comment by chrispyles** [comment]
Hi @champoll - the lack of a hard dependency on pdfkit and pypdf is intentional, as requiring them breaks the ability to install otter in some environments where its other functionality is useful (e.g. jupyterlite). w.r.t. matplotlib, it's not part of otter's dependencies because it's not used anywhere in the package, it's just part of the tutorial.

It may be possible to make pdfkit and pypdf part of the installation dependencies, as long as conda-forge's recipes support the same [`sys_platform` syntax](https://github.com/ucbds-infra/otter-grader/blob/master/requirements.txt#L14) that `requirements.txt` supports. I'll look into that.

**Comment by champoll** [comment]
That makes sense, thanks! That being said, It's helpful to have an ipynb file that can be used to check that otter-grader works correctly after installation. Perhaps another file could be used for that purpose instead of demo.ipynb, one that's closer to a minimal working example?

**Comment by chrispyles** [comment]
Conda doesn't support specifying the platform this way. Instead, I've opened #704 which adds a simple notebook which shouldn't require any of these packages to validation environments with. It can be found in the `examples` directory of the repo.
