### ISSUE TITLE
Following the tutorial on grading locally results in error message for "otter grade"

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#705]
**Describe the bug**
Following the [tutorial](https://otter-grader.readthedocs.io/en/latest/tutorial.html) on grading locally results in error message when running the command `otter grade -n demo -a dist/autograder/demo-autograder_*.zip --pdfs -v submissions/ipynbs`

**To Reproduce**
1. Download tutorial file
2. unzip tutorial.zip
3. otter assign demo.ipynb dist
4. otter grade -n demo -a dist/autograder/demo-autograder_*.zip --pdfs -v submissions/ipynbs
5. See error

**Expected behavior**
There should be no error. 

**Versions**
Python version: 3.10.12
Otter-Grader version: 5.1.1

**Additional context**
```
(otter-env) champollion@LucasChLate2016 tutorial2023 % unzip tutorial.zip 
Archive:  tutorial.zip
   creating: submissions/
   creating: submissions/ipynbs/
  inflating: submissions/ipynbs/demo-fails2.ipynb  
  inflating: submissions/ipynbs/demo-fails3Hidden.ipynb  
  inflating: submissions/ipynbs/demo-fails3.ipynb  
  inflating: submissions/ipynbs/demo-fails1.ipynb  
  inflating: submissions/ipynbs/demo-fails2Hidden.ipynb  
  inflating: submissions/ipynbs/demo-passesAll.ipynb  
   creating: submissions/zips/
 extracting: submissions/zips/demo-passesAll.zip  
 extracting: submissions/zips/demo-fails3Hidden.zip  
 extracting: submissions/zips/demo-fails2Hidden.zip  
 extracting: submissions/zips/demo-fails3.zip  
 extracting: submissions/zips/demo-fails2.zip  
 extracting: submissions/zips/demo-fails1.zip  
  inflating: demo.ipynb              
 extracting: requirements.txt        
(otter-env) champollion@LucasChLate2016 tutorial2023 % ls
demo.ipynb		submissions
requirements.txt	tutorial.zip
(otter-env) champollion@LucasChLate2016 tutorial2023 % rm tutorial.zip 
(otter-env) champollion@LucasChLate2016 tutorial2023 % otter assign demo.ipynb 
/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Usage: otter assign [OPTIONS] MASTER RESULT
Try 'otter assign --help' for help.

Error: Missing argument 'RESULT'.
(otter-env) champollion@LucasChLate2016 tutorial2023 % otter assign demo.ipynb dist
/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
(otter-env) champollion@LucasChLate2016 tutorial2023 % cd dist/autograder 
(otter-env) champollion@LucasChLate2016 autograder % cd ../..
(otter-env) champollion@LucasChLate2016 tutorial2023 % otter grade -n demo -a dist/autograder/demo-autograder_*.zip --pdfs -v submissions/ipynbs

/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
[INFO otter.grade.main] Launching Docker containers
[INFO otter.grade.containers.build_image] Building image using ubuntu:22.04 as base image
Traceback (most recent call last):
  File "/Users/champollion/miniconda3/envs/otter-env/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/otter/cli.py", line 148, in grade_cli
    g = grade(*args, **kwargs)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/otter/grade/__init__.py", line 110, in main
    grade_dfs = launch_containers(
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/otter/grade/containers.py", line 102, in launch_containers
    image = build_image(ag_zip_path, base_image, tag, config)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/otter/grade/containers.py", line 59, in build_image
    docker.build(
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 394, in build
    if self._method_to_get_image(builder) == GetImageMethod.TAG:
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 433, in _method_to_get_image
    builder = self.inspect(builder)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 494, in inspect
    return Builder(self.client_config, x, is_immutable_id=False)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 38, in __init__
    super().__init__(client_config, "name", reference, is_immutable_id)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/python_on_whales/client_config.py", line 186, in __init__
    self._fetch_and_parse_inspect_result(reference_or_id)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 53, in _fetch_and_parse_inspect_result
    return BuilderInspectResult.from_str(inspect_str)
  File "/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/python_on_whales/components/buildx/models.py", line 30, in from_str
    return cls(**result_dict)
TypeError: BuilderInspectResult.__init__() missing 1 required positional argument: 'status'
(otter-env) champollion@LucasChLate2016 tutorial2023 % otter --version
/Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
  _________        __          __               
 /  _____  \    __|  |__    __|  |__               
|  /     \  |  |__    __|  |__    __|   _______    _  _____
| |       | |     |  |        |  |     |  ___  |  | |/ ____|
| |       | |     |  |        |  |     | |___| |  |   /    
| |       | |     |  |        |  |     | ______|  |  |
|  \_____/  |     |  |_       |  |_    | |_____   |  |
 \_________/       \ __|       \ __|    \______|  |__|
                                                v5.1.1

Python version: 3.10.12
Otter-Grader version: 5.1.1
(otter-env) champollion@LucasChLate2016 tutorial2023 % 
```

**Comment by chrispyles** [comment]
@champoll what version of python-on-whales do you have? You can find out by running `pip show python-on-whales` in your conda environment.

**Comment by champoll** [comment]
(otter-env) champollion@LucasChLate2016 tutorial2023 % pip show python-on-whales                                                                
Name: python-on-whales
Version: 0.64.0
Summary: A Docker client for Python, designed to be fun and intuitive!
Home-page: 
Author: 
Author-email: 
License: MIT
Location: /Users/champollion/miniconda3/envs/otter-env/lib/python3.10/site-packages
Requires: pydantic, requests, tqdm, typer, typing-extensions
Required-by: otter-grader
(otter-env) champollion@LucasChLate2016 tutorial2023 %

**Comment by chrispyles** [comment]
@champoll I'm not sure that this is an issue with Otter... I think it's either an issue with your local Docker setup or with python-on-whales. Looking at its [repo](https://github.com/gabrieldemarmiesse/python-on-whales), I don't see any similar issues. It looks like it's failing when trying to run `docker buildx inspect`. What happens when you run that command on your machine?

**Comment by champoll** [comment]
```
(otter-env) champollion@LucasChLate2016 tutorial2023 % docker buildx inspect
docker: 'buildx' is not a docker command.
See 'docker --help'
(otter-env) champollion@LucasChLate2016 tutorial2023 % 
```

**Comment by chrispyles** [comment]
It looks like you don't have Docker buildx installed. I'm not sure if it's a hard requirement for python-on-whales or if python-on-whales can be used without it. I'd recommend installing buildx if possible ([more info](https://docs.docker.com/build/architecture/)) or opening an issue on their repo if that's not possible.
