### ISSUE TITLE
Cannot run grade

### ISSUE THREAD

**Issue by lrfinotti** [ucbds-infra/otter-grader#808]
Trying to follow the tutorial, the grading part fails:

```
$ otter grade -n demo -a dist/autograder/demo-autograder_*.zip --pdfs -v submissions/ipynbs
[INFO otter.grade.main] Launching Docker containers
[INFO otter.grade.containers.build_image] Building image using ubuntu:22.04 as base image
Traceback (most recent call last):
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/otter/grade/containers.py", line 60, in build_image
    docker.build(
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 405, in build
    if self._method_to_get_image(builder) == GetImageMethod.TAG:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 444, in _method_to_get_image
    builder = self.inspect(builder)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 510, in inspect
    return Builder(self.client_config, x, is_immutable_id=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 49, in __init__
    super().__init__(client_config, "name", reference, is_immutable_id)
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/python_on_whales/client_config.py", line 187, in __init__
    self._fetch_and_parse_inspect_result(reference_or_id)
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 64, in _fetch_and_parse_inspect_result
    return BuilderInspectResult.from_str(inspect_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/python_on_whales/components/buildx/models.py", line 30, in from_str
    return cls(**result_dict)
           ^^^^^^^^^^^^^^^^^^
TypeError: BuilderInspectResult.__init__() missing 1 required positional argument: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/finotti/.venvs/DS/bin/otter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/otter/cli.py", line 149, in grade_cli
    g = grade(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/otter/grade/__init__.py", line 110, in main
    grade_dfs = launch_containers(
                ^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/otter/grade/containers.py", line 107, in launch_containers
    image = build_image(ag_zip_path, base_image, tag, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finotti/.venvs/DS/lib/python3.11/site-packages/otter/grade/containers.py", line 68, in build_image
    raise TypeError(
TypeError: Docker build failed; if this is your first time seeing this error, ensure that Docker is running on your machine.

Original error: {e}
```

All steps before this one succeeded.

Note that docker is installed and running (as a service):

```
$ apt policy docker-ce
docker-ce:
  Installed: 5:27.0.1-1~debian.12~bookworm
  Candidate: 5:27.0.1-1~debian.12~bookworm
  Version table:
 *** 5:27.0.1-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
        100 /var/lib/dpkg/status
     5:26.1.4-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:26.1.3-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:26.1.2-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:26.1.1-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:26.1.0-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:26.0.2-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:26.0.1-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:26.0.0-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:25.0.5-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:25.0.4-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:25.0.3-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:25.0.2-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:25.0.1-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:25.0.0-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.9-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.8-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.7-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.6-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.5-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.4-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.3-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.2-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.1-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:24.0.0-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:23.0.6-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:23.0.5-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:23.0.4-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:23.0.3-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:23.0.2-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:23.0.1-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
     5:23.0.0-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
```

```
# docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

```
# service docker status
● docker.service - Docker Application Container Engine
     Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-06-26 09:29:05 EDT; 13min ago
 Invocation: b4afbcd80f164a1bbd1be0b289f49fda
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 326660 (dockerd)
      Tasks: 23
     Memory: 32.1M (peak: 34.8M)
        CPU: 676ms
     CGroup: /system.slice/docker.service
             └─326660 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Jun 26 09:29:04 dell7010 dockerd[326660]: time="2024-06-26T09:29:04.794192994-04:00" level=info msg="Loading containers: start."
Jun 26 09:29:05 dell7010 dockerd[326660]: time="2024-06-26T09:29:05.353536491-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jun 26 09:29:05 dell7010 dockerd[326660]: time="2024-06-26T09:29:05.422428833-04:00" level=info msg="Loading containers: done."
Jun 26 09:29:05 dell7010 dockerd[326660]: time="2024-06-26T09:29:05.428105300-04:00" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled" storage-driver=overlay2
Jun 26 09:29:05 dell7010 dockerd[326660]: time="2024-06-26T09:29:05.428210193-04:00" level=info msg="Docker daemon" commit=ff1e2c0 containerd-snapshotter=false storage-driver=overlay2 version=27.0.1
Jun 26 09:29:05 dell7010 dockerd[326660]: time="2024-06-26T09:29:05.428251240-04:00" level=info msg="Daemon has completed initialization"
Jun 26 09:29:05 dell7010 dockerd[326660]: time="2024-06-26T09:29:05.473028817-04:00" level=info msg="API listen on /run/docker.sock"
Jun 26 09:29:05 dell7010 systemd[1]: Started docker.service - Docker Application Container Engine.
Jun 26 09:31:44 dell7010 dockerd[326660]: time="2024-06-26T09:31:44.561687174-04:00" level=info msg="ignoring event" container=5acfe241dc28748c42f3a9cd0d39b0ad50b47f4e1b08a14f4946d2ac1b856975 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 26 09:41:58 dell7010 dockerd[326660]: time="2024-06-26T09:41:58.480638910-04:00" level=info msg="ignoring event" container=2154318d21be095ec168fcfeafda38452493dbf415c1abdc8c679517aaff470c module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

I am running Debian Sid/Unstable:

```
$ inxi -v3
System:
  Host: dell7010 Kernel: 6.9.6-1-siduction-amd64 arch: x86_64 bits: 64
    compiler: gcc v: 13.3.0
  Desktop: KDE Plasma v: 5.27.11 Distro: siduction 22.1.2 Masters_of_War -
    kde - (202303220911) base: Debian GNU/Linux trixie/sid
Machine:
  Type: Desktop System: Dell product: OptiPlex SFF Plus 7010 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 0YGWFV v: A00 serial: <superuser required> UEFI: Dell
    v: 1.14.0 date: 04/11/2024
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master 3
    charge: 55% (should be ignored) status: discharging
CPU:
  Info: 24-core model: 13th Gen Intel Core i9-13900 bits: 64 type: MCP
    arch: Raptor Lake rev: 1 cache: L1: 2.1 MiB L2: 32 MiB L3: 36 MiB
  Speed (MHz): avg: 846 high: 1143 min/max: 800/5300:5600:4200 cores: 1: 800
    2: 800 3: 800 4: 800 5: 800 6: 1100 7: 800 8: 1045 9: 1143 10: 800 11: 1022
    12: 800 13: 800 14: 800 15: 800 16: 800 17: 800 18: 800 19: 800 20: 800
    21: 800 22: 800 23: 800 24: 800 bogomips: 95846
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Raptor Lake-S GT1 [UHD Graphics 770] vendor: Dell
    driver: i915 v: kernel arch: Gen-13 bus-ID: 00:02.0
  Device-2: AMD Navi 24 [Radeon RX 6300] vendor: Dell driver: amdgpu
    v: kernel arch: RDNA-2 bus-ID: 03:00.0
  Device-3: Logitech C920 PRO HD Webcam driver: snd-usb-audio,uvcvideo
    type: USB bus-ID: 1-10:6
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 24.1.0 driver: X:
    loaded: amdgpu,modesetting unloaded: fbdev,radeon,vesa dri: iris
    gpu: amdgpu,i915 resolution: 1: 1920x1200~60Hz 2: 1080x1920~60Hz
    3: 2560x1440~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.1-2 glx-v: 1.4
    direct-render: yes renderer: Mesa Intel Graphics (RPL-S)
Network:
  Device-1: Intel Ethernet I219-LM vendor: Dell driver: e1000e v: kernel
    port: N/A bus-ID: 00:1f.6
  IF: enp0s31f6 state: up speed: 100 Mbps duplex: full
    mac: cc:96:e5:1f:61:3b
  IF-ID-1: docker0 state: down mac: 02:42:dd:f4:dc:43
  IF-ID-2: mpqemubr0 state: down mac: 52:54:00:75:a6:00
Drives:
  Local Storage: total: 953.88 GiB used: 663.05 GiB (69.5%)
Info:
  Memory: total: 128 GiB note: est. available: 125.51 GiB
    used: 13.17 GiB (10.5%)
  Processes: 552 Uptime: 58m Init: systemd target: graphical (5)
  Packages: 4512 Compilers: gcc: 13.3.0 Shell: Bash v: 5.2.21 inxi: 3.3.35
```

I am running Python 3.11.9 and otter-grader version 5.5.0.

**Comment by chrispyles** [comment]
This looks like either a bug in python-on-whales or an issue with your Docker setup. Can you send the output of `docker buildx inspect`?

**Comment by lrfinotti** [comment]
Thanks for the reply!  It would really be incredibly useful to have otter working for next Fall...

If I do not run is as root, it fails:

[code]
```
docker buildx inspect
Name:   default
Driver:
Error:  permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
```

As root, it gives the following:

```
sudo docker buildx inspect
[sudo] password for finotti:
Name:   default
Driver: docker

Nodes:
Name:             default
Endpoint:         default
Status:           running
BuildKit version: v0.14.1
Platforms:        linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
Labels:
 org.mobyproject.buildkit.worker.moby.host-gateway-ip: 172.17.0.1
```

I assume we do not need to run otter as root, correct?

**Comment by lrfinotti** [comment]
Ah, so I what I needed to do was to add my regular user to the `docker` group!  Now this step of the tutorial worked!

Thanks for your help!  I would not have found this out if it were not for your comment.  (I'd never used docker before.)

I will leave for someone else to close the issue, just in case...

**Comment by chrispyles** [comment]
Glad to hear it's working. Yes, in this case, the correct resolution was to add your user to the `docker` group.

Going to go ahead and close this.
