### ISSUE TITLE
R image build requires mamba gcc_linux-64 and gxx_linux-64

### ISSUE THREAD

**Issue by paulamarm** [ucbds-infra/otter-grader#819]
**Describe the bug**

I have been seeing the issue when generating the assignment files for the PH142 class that the rpy2 module can't be found. It wasn't affecting the gradescope passing until I'm now seeing the same feedback described by the user in post #725 where the otter module can't be found. I just updated the version of R that my R-studio is using as an attempt to resolve this and have had no success with updating rpy2- it gets stuck in a cycle.

Following this post, I upzipped the autograder, removed the rpy2 line from the environment.yml file which didn't work so I've reverted to the basic settings and am trying to understand why it won't recognize the otter module in gradescope when running the autograder zipfile. I updated otter and otter-grader in the datahub as well, which also didn't fix the issue. 

Because I see that the rpy2 module has depreciated/ evolved, I wanted to ask what's the best way for me to approach this issue!
Thanks!

**To Reproduce**
1. Files: 
-    turnitin.py with gradescope assignment and submission info, otherwise unchanged since prior versions of R
- requirements.R file (attached)
- the assignment document, with the following configuration settings:

**Run this chunk of code to load the autograder package!**
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(testthat)
```

- ... also a data folder, src folder, and some prior semester folders of the assignment 

_(pretending the assignment name is file instead of lab10, what it truly is named )_

2. go to directory and run ` otter assign file.Rmd file-su24 `

3. See error: 

Traceback (most recent call last):
  File "/Users/paulamarquez/opt/anaconda3/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/cli.py", line 64, in assign_cli
    return assign(*args, **kwargs)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/assign/__init__.py", line 157, in main
    run_tests(assignment, debug=debug)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/assign/utils.py", line 221, in run_tests
    results = grade_submission(
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/api.py", line 49, in grade_submission
    results = run_grader(
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/run/__init__.py", line 60, in main
    run_autograder_main(ag_dir, logo=logo, debug=debug, otter_run=True)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/run/run_autograder/__init__.py", line 44, in main
    runner = create_runner(config, autograder_dir=autograder_dir, **kwargs)
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/run/run_autograder/runners/__init__.py", line 16, in create_runner
    from .r_runner import RRunner
  File "/Users/paulamarquez/opt/anaconda3/lib/python3.9/site-packages/otter/run/run_autograder/runners/r_runner.py", line 12, in <module>
    from rpy2.robjects.packages import importr
ModuleNotFoundError: No module named 'rpy2'

... the file-su24 folder is then produced, but the autograder fails with the same error message seen in #725 

**Expected behavior**
Produce the file-su24 folder with the autograder and student files, which pass the cases both when accessed and ran by students in datahub and when submitted in gradescope

**Versions**
Python 3.9.12 on Anaconda 
 R version 4.4.1 (2024-06-14)

**Additional context**
This is the same class in which students were experiencing issues with the turnitin.py line where they had GB worth of data in their terminal (https://github.com/berkeley-dsep-infra/datahub/issues/5886#issuecomment-2248519470). I experienced an issue like that this time when attempting to submit the lab on datahub, and had to clear my terminal and close R-studio to be able to run it again afterwards.

**Comment by chrispyles** [comment]
The `ModuleNotFoundError: No module named 'rpy2'` your're seeing when running `otter assign` is because rpy2 must be installed on your machine in order to work with R assignments in otter.

I'll look into the Gradescope build issue.

**Comment by chrispyles** [comment]
It looks like rpy2 needs to install gcc with mamba. adding `gcc_linux-64` and `gxx_linux-64` to the `environment.yml` in the autograder configuration zip file should fix the image build.

i'll leave this issue open to track adding this to the template in v5.6.0.

**Comment by paulamarm** [comment]
Thank you! In the meantime, can I make these changes myself in the environment.yml file, and would it be as either a dependency or pip module?

**Comment by chrispyles** [comment]
Yes you can do this manually; they should be added under `dependencies` not as pip modules.

**Comment by paulamarm** [comment]
Thank you! Both assignments now pass all tests on gradescope with the adjustment.
