### ISSUE TITLE
Getting two errors running otter assign

### ISSUE THREAD

**Issue by codingPie** [ucbds-infra/otter-grader#825]
**Describe the bug**
When running otter assign, I got two exceptions:
(base) C:\Users\jieli\Documents\Grading>otter assign Week2_Now_You_Try.ipynb dist
Traceback (most recent call last):
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\assign\__init__.py", line 95, in main
    export_notebook(
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\export\__init__.py", line 35, in export_notebook
    Exporter = get_exporter(exporter_type=exporter_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\export\exporters\__init__.py", line 30, in get_exporter
    raise WkhtmltopdfNotFoundError("PDF via HTML indicated but wkhtmltopdf not found")
otter.export.utils.WkhtmltopdfNotFoundError: PDF via HTML indicated but wkhtmltopdf not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jieli\AppData\Local\anaconda3\Scripts\otter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\cli.py", line 32, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\cli.py", line 64, in assign_cli
    return assign(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\assign\__init__.py", line 106, in main
    export_notebook(
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\export\__init__.py", line 36, in export_notebook
    Exporter.convert_notebook(nb_path, pdf_name, **kwargs)
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\export\exporters\via_latex.py", line 44, in convert_notebook
    nb = cls.load_notebook(nb_path, filtering=options["filtering"], pagebreaks=options["pagebreaks"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\otter\export\exporters\base_exporter.py", line 76, in load_notebook
    notebook = nbformat.read(f, as_version=NBFORMAT_VERSION)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\site-packages\nbformat\__init__.py", line 166, in read
    buf = fp.read()
          ^^^^^^^^^
  File "C:\Users\jieli\AppData\Local\anaconda3\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3290: character maps to <undefined>

**To Reproduce**
Run otter assign with the assignment file causes this error
The file is attached below as a zip file
[Week2_Now_You_Try.zip](https://github.com/user-attachments/files/16655569/Week2_Now_You_Try.zip)

**Expected behavior**
I should not see the errors and the PDF file and zip file should be created

**Versions**
Please provide your Python and Otter versions. The Otter can be obtained using `from otter import __version__`
Python: 3.11.5
Otter version: 5.5.0
Windows 11
wkhtmltopdf installed on c:\Program Files

**Additional context**
I was able to generate PDF and zip file using the files provided in tutorial.

**Comment by codingPie** [comment]
The problem went away after I removed cells and added them back one by one. I still don't know what was the problem since everything else was the same. I suspect it was caused by the triple quotes for test configuration. But I am glad it works now.
