### ISSUE TITLE
Otter Grade: AttributeError: 'GradingResults' object has no attribute '_catastrophic_error'

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#829]
**Describe the bug**
When running otter grade, an AttributeError is thrown on the '_catastrophic_error' attribute of the GradingResults object created after grading the notebooks

**To Reproduce**
1. Install 5.6.0
2. Run otter grade from the command line
3. You get: AttributeError: 'GradingResults' object has no attribute '_catastrophic_error'
4. For some reason, that I don't quite see, the GradingResults objects do not have the _catastrophic_error attribute unless there is an actual error.
5. If you study the (GradingResults object)[https://github.com/sean-morris/otter-grader/blob/c68a6ffe305de0b80a67c23e9a864e1042d4ed55/otter/test_files/__init__.py#L79], the _catastrophic_error attribute appears to be set to None in the constructor. 

**Expected behavior**
otter grade should not throw the AttributeError ever

**Versions**
5.6.0

**Suggested Fix**
Option 1: I can make sure the key exists on line 394 in test_files/__init__.py which stops the error
Option 2: I can add a procedure to the GradingResults class, set_catastrophic_error. Then call this procedure after a successful scores object is created -- which appears to be needed execute/__init__.py and grade/containers.py. 

My PR handles this with Option 2 

**Additional context**
The traceback:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/otter-grader/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/cli.py", line 150, in grade_cli
    g = grade(*args, **kwargs)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/grade/__init__.py", line 120, in main
    grade_dfs = launch_containers(
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/grade/containers.py", line 121, in launch_containers
    return merge_scores_to_df(scores)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/grade/utils.py", line 131, in merge_scores_to_df
    pts_poss_df = get_points_possible_df(scores)
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/grade/utils.py", line 106, in get_points_possible_df
    gr_completed = [s for s in scores if not s.has_catastrophic_failure()]
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/grade/utils.py", line 106, in <listcomp>
    gr_completed = [s for s in scores if not s.has_catastrophic_failure()]
  File "/opt/miniconda3/envs/otter-grader/lib/python3.10/site-packages/otter/test_files/__init__.py", line 394, in has_catastrophic_failure
    return self._catastrophic_error is not None
AttributeError: 'GradingResults' object has no attribute '_catastrophic_error'

**Comment by chrispyles** [comment]
This seems like a version mismatch issue -- what version of Otter is on your system vs. what version is running in the container?

**Comment by sean-morris** [comment]
ahhhhh. OK wait a second

**Comment by chrispyles** [comment]
Did you figure out what the issue was here?

**Comment by sean-morris** [comment]
Not yet.  I will look today. I am sure you are right. This introduce then
total break from version 4 which is fine.

I am just about to PR progress monitoring. I will need your feedback here.

**Comment by sean-morris** [comment]
using old autograder.zip
