### ISSUE TITLE
Setting a specific version of pandas (2.1.4) in notebook requirements breaks autograder

### ISSUE THREAD

**Issue by glciampaglia** [ucbds-infra/otter-grader#891]
**Describe the bug**
I am trying to pin pandas to a specific version to ensure submissions of students are graded in an environment consistent with the one they had when developing their code. (Long story short, but on newer versions of Pandas their code would produce a different output thus failing the tests on Gradescope.) 

I discovered that pinning pandas to version 2.1.4 creates images were the autograder is broken, both locally via `otter grade` and on Gradescope. It seems to be a version-specific behavior because when I pin to version 2.2.0. 

**To Reproduce**

Here is my assignment config
```yaml
# ASSIGNMENT CONFIG
files:
    - bls-by-category.csv
    - BreadBasket_DMS.csv
    - ncaa-team-data.csv
    - testudo_fall2020.csv
    - testudo_fall2020_random.csv
    - bls-by-category-random.csv
    - ncaa-team-data-random.csv
    - BreadBasket_DMS_random.csv
tests:
    ok_format: false
export_cell:
    pdf: false
    run_tests: true
    force_save: true
    files:
        - PR-04-Pandas.py
generate: 
    points_possible: 2
    score_threshold: 0.24
    filtering: true
    zips: false
    show_stdout: true
requirements:
    - pandas==2.1.4
```

Running
```
otter grade -n PR-04 -a dist/autograder/PR-04-Pandas-autograder_*.zip submissions/zips --ext zip -v --debug
```
Yields
```
[INFO otter.grade.containers.launch_containers] Notebooks to grade: 2
[INFO otter.grade.containers.grade_submission] Grading 295550689.zip
[INFO otter.grade.containers.grade_submission] Grading 296297782.zip
[ERROR otter.grade.containers.grade_submission] An error occurred while grading "295550689.zip":
  > Traceback (most recent call last):
  >   File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/otter/grade/containers.py", line 233, in grade_submission
  >     raise Exception(
  > Exception: Executing 'submissions/zips/295550689.zip' in docker container failed! Exit code: 1

[INFO otter.grade.containers.launch_containers] 295550689.zip complete: 1/2
[ERROR otter.grade.containers.grade_submission] An error occurred while grading "296297782.zip":
  > Traceback (most recent call last):
  >   File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/otter/grade/containers.py", line 233, in grade_submission
  >     raise Exception(
  > Exception: Executing 'submissions/zips/296297782.zip' in docker container failed! Exit code: 1

[INFO otter.grade.containers.launch_containers] 296297782.zip complete: 2/2
[INFO otter.grade.containers.launch_containers] Notebooks graded: 2
[INFO otter.grade.main] Combining grades and saving
```

While running
```
otter grade -n PR-04 -a dist/autograder/PR-04-Pandas-autograder_*.zip submissions/ipynb/PR-04-Pandas-2955.ipynb
```
Yields
```
[ERROR otter.grade.containers.grade_submission] An error occurred while grading "PR-04-Pandas-2955.ipynb":
  > Traceback (most recent call last):
  >   File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/otter/grade/containers.py", line 233, in grade_submission
  >     raise Exception(
  > Exception: Executing 'submissions/ipynb/PR-04-Pandas-2955.ipynb' in docker container failed! Exit code: 1

Traceback (most recent call last):
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 414, in get_loc
    return self._range.index(new_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 1 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/giovanni/miniconda3/envs/inst126debug/bin/otter", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/otter/cli.py", line 32, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/otter/cli.py", line 253, in grade_cli
    g = grade(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/otter/grade/__init__.py", line 166, in main
    return output_df[SCORES_DICT_PERCENT_CORRECT_KEY][1]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/pandas/core/series.py", line 1040, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/pandas/core/series.py", line 1156, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/miniconda3/envs/inst126debug/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 416, in get_loc
    raise KeyError(key) from err
KeyError: 1
```

On Gradescope I have been getting:
```python
Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 3, in <module>
    from otter.run.run_autograder import main as run_autograder
ModuleNotFoundError: No module named 'otter'
```

If I set
```yaml
requirements:
    - pandas==2.2.0
```
In the assignment config the grader works fine both locally and on gradescope

**Expected behavior**
The grader should work regardless of the pinned pandas version

**Versions**
Otter 6.0.4
Python 3.12.7

**Comment by chrispyles** [comment]
The error you're seeing on Gradescope is indicative of an error while building the grading image. Can you share the image build output from Gradescope and/or local?

To rebuild the local image, you will need to delete the existing grading image with `docker rmi otter-grade:PR-04`.

**Comment by chrispyles** [comment]
bump @glciampaglia

**Comment by glciampaglia** [comment]
I tried to reproduce the issue, but I am not able anymore. Perhaps it was just a glitch of the package manager that was cached. I'll close for now and if it happens again I'll reopen it with the info you asked, @chrispyles. Thanks a lot of checking on this, and for making otter. It's my second semester running it and things have been a huge improvement since migrating from nbgrader!
